const data = [
  {
    RouteID: "G-1",
    LineID: "G",
    StationID: "G01",
    StationName: {
      Zh_tw: "新店",
      En: "Xindian",
    },
    Direction: 0,
    DestinationStaionID: "G19",
    DestinationStationName: {
      Zh_tw: "松山",
      En: "Songshan",
    },
    Timetables: [
      {
        Sequence: 1,
        ArrivalTime: "06:00",
        DepartureTime: "06:00",
        TrainType: 0,
      },
      {
        Sequence: 2,
        ArrivalTime: "06:08",
        DepartureTime: "06:08",
        TrainType: 0,
      },
      {
        Sequence: 3,
        ArrivalTime: "06:17",
        DepartureTime: "06:17",
        TrainType: 0,
      },
      {
        Sequence: 4,
        ArrivalTime: "06:25",
        DepartureTime: "06:25",
        TrainType: 0,
      },
      {
        Sequence: 5,
        ArrivalTime: "06:32",
        DepartureTime: "06:32",
        TrainType: 0,
      },
      {
        Sequence: 6,
        ArrivalTime: "06:37",
        DepartureTime: "06:37",
        TrainType: 0,
      },
      {
        Sequence: 7,
        ArrivalTime: "06:40",
        DepartureTime: "06:40",
        TrainType: 0,
      },
      {
        Sequence: 8,
        ArrivalTime: "06:46",
        DepartureTime: "06:46",
        TrainType: 0,
      },
      {
        Sequence: 9,
        ArrivalTime: "06:54",
        DepartureTime: "06:54",
        TrainType: 0,
      },
      {
        Sequence: 10,
        ArrivalTime: "07:00",
        DepartureTime: "07:00",
        TrainType: 0,
      },
      {
        Sequence: 11,
        ArrivalTime: "07:05",
        DepartureTime: "07:05",
        TrainType: 0,
      },
      {
        Sequence: 12,
        ArrivalTime: "07:11",
        DepartureTime: "07:11",
        TrainType: 0,
      },
      {
        Sequence: 13,
        ArrivalTime: "07:17",
        DepartureTime: "07:17",
        TrainType: 0,
      },
      {
        Sequence: 14,
        ArrivalTime: "07:21",
        DepartureTime: "07:21",
        TrainType: 0,
      },
      {
        Sequence: 15,
        ArrivalTime: "07:24",
        DepartureTime: "07:24",
        TrainType: 0,
      },
      {
        Sequence: 16,
        ArrivalTime: "07:29",
        DepartureTime: "07:29",
        TrainType: 0,
      },
      {
        Sequence: 17,
        ArrivalTime: "07:33",
        DepartureTime: "07:33",
        TrainType: 0,
      },
      {
        Sequence: 18,
        ArrivalTime: "07:36",
        DepartureTime: "07:36",
        TrainType: 0,
      },
      {
        Sequence: 19,
        ArrivalTime: "07:41",
        DepartureTime: "07:41",
        TrainType: 0,
      },
      {
        Sequence: 20,
        ArrivalTime: "07:45",
        DepartureTime: "07:45",
        TrainType: 0,
      },
      {
        Sequence: 21,
        ArrivalTime: "07:48",
        DepartureTime: "07:48",
        TrainType: 0,
      },
      {
        Sequence: 22,
        ArrivalTime: "07:53",
        DepartureTime: "07:53",
        TrainType: 0,
      },
      {
        Sequence: 23,
        ArrivalTime: "07:57",
        DepartureTime: "07:57",
        TrainType: 0,
      },
      {
        Sequence: 24,
        ArrivalTime: "08:00",
        DepartureTime: "08:00",
        TrainType: 0,
      },
      {
        Sequence: 25,
        ArrivalTime: "08:05",
        DepartureTime: "08:05",
        TrainType: 0,
      },
      {
        Sequence: 26,
        ArrivalTime: "08:09",
        DepartureTime: "08:09",
        TrainType: 0,
      },
      {
        Sequence: 27,
        ArrivalTime: "08:12",
        DepartureTime: "08:12",
        TrainType: 0,
      },
      {
        Sequence: 28,
        ArrivalTime: "08:17",
        DepartureTime: "08:17",
        TrainType: 0,
      },
      {
        Sequence: 29,
        ArrivalTime: "08:21",
        DepartureTime: "08:21",
        TrainType: 0,
      },
      {
        Sequence: 30,
        ArrivalTime: "08:24",
        DepartureTime: "08:24",
        TrainType: 0,
      },
      {
        Sequence: 31,
        ArrivalTime: "08:29",
        DepartureTime: "08:29",
        TrainType: 0,
      },
      {
        Sequence: 32,
        ArrivalTime: "08:33",
        DepartureTime: "08:33",
        TrainType: 0,
      },
      {
        Sequence: 33,
        ArrivalTime: "08:36",
        DepartureTime: "08:36",
        TrainType: 0,
      },
      {
        Sequence: 34,
        ArrivalTime: "08:41",
        DepartureTime: "08:41",
        TrainType: 0,
      },
      {
        Sequence: 35,
        ArrivalTime: "08:45",
        DepartureTime: "08:45",
        TrainType: 0,
      },
      {
        Sequence: 36,
        ArrivalTime: "08:48",
        DepartureTime: "08:48",
        TrainType: 0,
      },
      {
        Sequence: 37,
        ArrivalTime: "08:54",
        DepartureTime: "08:54",
        TrainType: 0,
      },
      {
        Sequence: 38,
        ArrivalTime: "08:58",
        DepartureTime: "08:58",
        TrainType: 0,
      },
      {
        Sequence: 39,
        ArrivalTime: "09:00",
        DepartureTime: "09:00",
        TrainType: 0,
      },
      {
        Sequence: 40,
        ArrivalTime: "09:06",
        DepartureTime: "09:06",
        TrainType: 0,
      },
      {
        Sequence: 41,
        ArrivalTime: "09:13",
        DepartureTime: "09:13",
        TrainType: 0,
      },
      {
        Sequence: 42,
        ArrivalTime: "09:16",
        DepartureTime: "09:16",
        TrainType: 0,
      },
      {
        Sequence: 43,
        ArrivalTime: "09:22",
        DepartureTime: "09:22",
        TrainType: 0,
      },
      {
        Sequence: 44,
        ArrivalTime: "09:25",
        DepartureTime: "09:25",
        TrainType: 0,
      },
      {
        Sequence: 45,
        ArrivalTime: "09:30",
        DepartureTime: "09:30",
        TrainType: 0,
      },
      {
        Sequence: 46,
        ArrivalTime: "09:34",
        DepartureTime: "09:34",
        TrainType: 0,
      },
      {
        Sequence: 47,
        ArrivalTime: "09:41",
        DepartureTime: "09:41",
        TrainType: 0,
      },
      {
        Sequence: 48,
        ArrivalTime: "09:44",
        DepartureTime: "09:44",
        TrainType: 0,
      },
      {
        Sequence: 49,
        ArrivalTime: "09:49",
        DepartureTime: "09:49",
        TrainType: 0,
      },
      {
        Sequence: 50,
        ArrivalTime: "09:54",
        DepartureTime: "09:54",
        TrainType: 0,
      },
      {
        Sequence: 51,
        ArrivalTime: "10:02",
        DepartureTime: "10:02",
        TrainType: 0,
      },
      {
        Sequence: 52,
        ArrivalTime: "10:10",
        DepartureTime: "10:10",
        TrainType: 0,
      },
      {
        Sequence: 53,
        ArrivalTime: "10:18",
        DepartureTime: "10:18",
        TrainType: 0,
      },
      {
        Sequence: 54,
        ArrivalTime: "10:23",
        DepartureTime: "10:23",
        TrainType: 0,
      },
      {
        Sequence: 55,
        ArrivalTime: "10:31",
        DepartureTime: "10:31",
        TrainType: 0,
      },
      {
        Sequence: 56,
        ArrivalTime: "10:38",
        DepartureTime: "10:38",
        TrainType: 0,
      },
      {
        Sequence: 57,
        ArrivalTime: "10:46",
        DepartureTime: "10:46",
        TrainType: 0,
      },
      {
        Sequence: 58,
        ArrivalTime: "10:54",
        DepartureTime: "10:54",
        TrainType: 0,
      },
      {
        Sequence: 59,
        ArrivalTime: "11:00",
        DepartureTime: "11:00",
        TrainType: 0,
      },
      {
        Sequence: 60,
        ArrivalTime: "11:07",
        DepartureTime: "11:07",
        TrainType: 0,
      },
      {
        Sequence: 61,
        ArrivalTime: "11:14",
        DepartureTime: "11:14",
        TrainType: 0,
      },
      {
        Sequence: 62,
        ArrivalTime: "11:22",
        DepartureTime: "11:22",
        TrainType: 0,
      },
      {
        Sequence: 63,
        ArrivalTime: "11:30",
        DepartureTime: "11:30",
        TrainType: 0,
      },
      {
        Sequence: 64,
        ArrivalTime: "11:36",
        DepartureTime: "11:36",
        TrainType: 0,
      },
      {
        Sequence: 65,
        ArrivalTime: "11:43",
        DepartureTime: "11:43",
        TrainType: 0,
      },
      {
        Sequence: 66,
        ArrivalTime: "11:50",
        DepartureTime: "11:50",
        TrainType: 0,
      },
      {
        Sequence: 67,
        ArrivalTime: "11:58",
        DepartureTime: "11:58",
        TrainType: 0,
      },
      {
        Sequence: 68,
        ArrivalTime: "12:06",
        DepartureTime: "12:06",
        TrainType: 0,
      },
      {
        Sequence: 69,
        ArrivalTime: "12:12",
        DepartureTime: "12:12",
        TrainType: 0,
      },
      {
        Sequence: 70,
        ArrivalTime: "12:19",
        DepartureTime: "12:19",
        TrainType: 0,
      },
      {
        Sequence: 71,
        ArrivalTime: "12:26",
        DepartureTime: "12:26",
        TrainType: 0,
      },
      {
        Sequence: 72,
        ArrivalTime: "12:34",
        DepartureTime: "12:34",
        TrainType: 0,
      },
      {
        Sequence: 73,
        ArrivalTime: "12:42",
        DepartureTime: "12:42",
        TrainType: 0,
      },
      {
        Sequence: 74,
        ArrivalTime: "12:48",
        DepartureTime: "12:48",
        TrainType: 0,
      },
      {
        Sequence: 75,
        ArrivalTime: "12:55",
        DepartureTime: "12:55",
        TrainType: 0,
      },
      {
        Sequence: 76,
        ArrivalTime: "13:02",
        DepartureTime: "13:02",
        TrainType: 0,
      },
      {
        Sequence: 77,
        ArrivalTime: "13:10",
        DepartureTime: "13:10",
        TrainType: 0,
      },
      {
        Sequence: 78,
        ArrivalTime: "13:18",
        DepartureTime: "13:18",
        TrainType: 0,
      },
      {
        Sequence: 79,
        ArrivalTime: "13:24",
        DepartureTime: "13:24",
        TrainType: 0,
      },
      {
        Sequence: 80,
        ArrivalTime: "13:31",
        DepartureTime: "13:31",
        TrainType: 0,
      },
      {
        Sequence: 81,
        ArrivalTime: "13:38",
        DepartureTime: "13:38",
        TrainType: 0,
      },
      {
        Sequence: 82,
        ArrivalTime: "13:46",
        DepartureTime: "13:46",
        TrainType: 0,
      },
      {
        Sequence: 83,
        ArrivalTime: "13:54",
        DepartureTime: "13:54",
        TrainType: 0,
      },
      {
        Sequence: 84,
        ArrivalTime: "14:00",
        DepartureTime: "14:00",
        TrainType: 0,
      },
      {
        Sequence: 85,
        ArrivalTime: "14:07",
        DepartureTime: "14:07",
        TrainType: 0,
      },
      {
        Sequence: 86,
        ArrivalTime: "14:14",
        DepartureTime: "14:14",
        TrainType: 0,
      },
      {
        Sequence: 87,
        ArrivalTime: "14:22",
        DepartureTime: "14:22",
        TrainType: 0,
      },
      {
        Sequence: 88,
        ArrivalTime: "14:30",
        DepartureTime: "14:30",
        TrainType: 0,
      },
      {
        Sequence: 89,
        ArrivalTime: "14:36",
        DepartureTime: "14:36",
        TrainType: 0,
      },
      {
        Sequence: 90,
        ArrivalTime: "14:43",
        DepartureTime: "14:43",
        TrainType: 0,
      },
      {
        Sequence: 91,
        ArrivalTime: "14:50",
        DepartureTime: "14:50",
        TrainType: 0,
      },
      {
        Sequence: 92,
        ArrivalTime: "14:58",
        DepartureTime: "14:58",
        TrainType: 0,
      },
      {
        Sequence: 93,
        ArrivalTime: "15:06",
        DepartureTime: "15:06",
        TrainType: 0,
      },
      {
        Sequence: 94,
        ArrivalTime: "15:12",
        DepartureTime: "15:12",
        TrainType: 0,
      },
      {
        Sequence: 95,
        ArrivalTime: "15:19",
        DepartureTime: "15:19",
        TrainType: 0,
      },
      {
        Sequence: 96,
        ArrivalTime: "15:26",
        DepartureTime: "15:26",
        TrainType: 0,
      },
      {
        Sequence: 97,
        ArrivalTime: "15:34",
        DepartureTime: "15:34",
        TrainType: 0,
      },
      {
        Sequence: 98,
        ArrivalTime: "15:42",
        DepartureTime: "15:42",
        TrainType: 0,
      },
      {
        Sequence: 99,
        ArrivalTime: "15:48",
        DepartureTime: "15:48",
        TrainType: 0,
      },
      {
        Sequence: 100,
        ArrivalTime: "15:55",
        DepartureTime: "15:55",
        TrainType: 0,
      },
      {
        Sequence: 101,
        ArrivalTime: "16:02",
        DepartureTime: "16:02",
        TrainType: 0,
      },
      {
        Sequence: 102,
        ArrivalTime: "16:10",
        DepartureTime: "16:10",
        TrainType: 0,
      },
      {
        Sequence: 103,
        ArrivalTime: "16:18",
        DepartureTime: "16:18",
        TrainType: 0,
      },
      {
        Sequence: 104,
        ArrivalTime: "16:24",
        DepartureTime: "16:24",
        TrainType: 0,
      },
      {
        Sequence: 105,
        ArrivalTime: "16:29",
        DepartureTime: "16:29",
        TrainType: 0,
      },
      {
        Sequence: 106,
        ArrivalTime: "16:37",
        DepartureTime: "16:37",
        TrainType: 0,
      },
      {
        Sequence: 107,
        ArrivalTime: "16:45",
        DepartureTime: "16:45",
        TrainType: 0,
      },
      {
        Sequence: 108,
        ArrivalTime: "16:52",
        DepartureTime: "16:52",
        TrainType: 0,
      },
      {
        Sequence: 109,
        ArrivalTime: "16:59",
        DepartureTime: "16:59",
        TrainType: 0,
      },
      {
        Sequence: 110,
        ArrivalTime: "17:05",
        DepartureTime: "17:05",
        TrainType: 0,
      },
      {
        Sequence: 111,
        ArrivalTime: "17:12",
        DepartureTime: "17:12",
        TrainType: 0,
      },
      {
        Sequence: 112,
        ArrivalTime: "17:18",
        DepartureTime: "17:18",
        TrainType: 0,
      },
      {
        Sequence: 113,
        ArrivalTime: "17:21",
        DepartureTime: "17:21",
        TrainType: 0,
      },
      {
        Sequence: 114,
        ArrivalTime: "17:24",
        DepartureTime: "17:24",
        TrainType: 0,
      },
      {
        Sequence: 115,
        ArrivalTime: "17:31",
        DepartureTime: "17:31",
        TrainType: 0,
      },
      {
        Sequence: 116,
        ArrivalTime: "17:35",
        DepartureTime: "17:35",
        TrainType: 0,
      },
      {
        Sequence: 117,
        ArrivalTime: "17:38",
        DepartureTime: "17:38",
        TrainType: 0,
      },
      {
        Sequence: 118,
        ArrivalTime: "17:44",
        DepartureTime: "17:44",
        TrainType: 0,
      },
      {
        Sequence: 119,
        ArrivalTime: "17:48",
        DepartureTime: "17:48",
        TrainType: 0,
      },
      {
        Sequence: 120,
        ArrivalTime: "17:50",
        DepartureTime: "17:50",
        TrainType: 0,
      },
      {
        Sequence: 121,
        ArrivalTime: "17:57",
        DepartureTime: "17:57",
        TrainType: 0,
      },
      {
        Sequence: 122,
        ArrivalTime: "18:00",
        DepartureTime: "18:00",
        TrainType: 0,
      },
      {
        Sequence: 123,
        ArrivalTime: "18:03",
        DepartureTime: "18:03",
        TrainType: 0,
      },
      {
        Sequence: 124,
        ArrivalTime: "18:10",
        DepartureTime: "18:10",
        TrainType: 0,
      },
      {
        Sequence: 125,
        ArrivalTime: "18:13",
        DepartureTime: "18:13",
        TrainType: 0,
      },
      {
        Sequence: 126,
        ArrivalTime: "18:16",
        DepartureTime: "18:16",
        TrainType: 0,
      },
      {
        Sequence: 127,
        ArrivalTime: "18:22",
        DepartureTime: "18:22",
        TrainType: 0,
      },
      {
        Sequence: 128,
        ArrivalTime: "18:26",
        DepartureTime: "18:26",
        TrainType: 0,
      },
      {
        Sequence: 129,
        ArrivalTime: "18:28",
        DepartureTime: "18:28",
        TrainType: 0,
      },
      {
        Sequence: 130,
        ArrivalTime: "18:35",
        DepartureTime: "18:35",
        TrainType: 0,
      },
      {
        Sequence: 131,
        ArrivalTime: "18:38",
        DepartureTime: "18:38",
        TrainType: 0,
      },
      {
        Sequence: 132,
        ArrivalTime: "18:41",
        DepartureTime: "18:41",
        TrainType: 0,
      },
      {
        Sequence: 133,
        ArrivalTime: "18:48",
        DepartureTime: "18:48",
        TrainType: 0,
      },
      {
        Sequence: 134,
        ArrivalTime: "18:51",
        DepartureTime: "18:51",
        TrainType: 0,
      },
      {
        Sequence: 135,
        ArrivalTime: "18:54",
        DepartureTime: "18:54",
        TrainType: 0,
      },
      {
        Sequence: 136,
        ArrivalTime: "19:00",
        DepartureTime: "19:00",
        TrainType: 0,
      },
      {
        Sequence: 137,
        ArrivalTime: "19:04",
        DepartureTime: "19:04",
        TrainType: 0,
      },
      {
        Sequence: 138,
        ArrivalTime: "19:06",
        DepartureTime: "19:06",
        TrainType: 0,
      },
      {
        Sequence: 139,
        ArrivalTime: "19:13",
        DepartureTime: "19:13",
        TrainType: 0,
      },
      {
        Sequence: 140,
        ArrivalTime: "19:17",
        DepartureTime: "19:17",
        TrainType: 0,
      },
      {
        Sequence: 141,
        ArrivalTime: "19:20",
        DepartureTime: "19:20",
        TrainType: 0,
      },
      {
        Sequence: 142,
        ArrivalTime: "19:26",
        DepartureTime: "19:26",
        TrainType: 0,
      },
      {
        Sequence: 143,
        ArrivalTime: "19:31",
        DepartureTime: "19:31",
        TrainType: 0,
      },
      {
        Sequence: 144,
        ArrivalTime: "19:35",
        DepartureTime: "19:35",
        TrainType: 0,
      },
      {
        Sequence: 145,
        ArrivalTime: "19:40",
        DepartureTime: "19:40",
        TrainType: 0,
      },
      {
        Sequence: 146,
        ArrivalTime: "19:44",
        DepartureTime: "19:44",
        TrainType: 0,
      },
      {
        Sequence: 147,
        ArrivalTime: "19:48",
        DepartureTime: "19:48",
        TrainType: 0,
      },
      {
        Sequence: 148,
        ArrivalTime: "19:51",
        DepartureTime: "19:51",
        TrainType: 0,
      },
      {
        Sequence: 149,
        ArrivalTime: "19:55",
        DepartureTime: "19:55",
        TrainType: 0,
      },
      {
        Sequence: 150,
        ArrivalTime: "19:59",
        DepartureTime: "19:59",
        TrainType: 0,
      },
      {
        Sequence: 151,
        ArrivalTime: "20:05",
        DepartureTime: "20:05",
        TrainType: 0,
      },
      {
        Sequence: 152,
        ArrivalTime: "20:09",
        DepartureTime: "20:09",
        TrainType: 0,
      },
      {
        Sequence: 153,
        ArrivalTime: "20:14",
        DepartureTime: "20:14",
        TrainType: 0,
      },
      {
        Sequence: 154,
        ArrivalTime: "20:16",
        DepartureTime: "20:16",
        TrainType: 0,
      },
      {
        Sequence: 155,
        ArrivalTime: "20:22",
        DepartureTime: "20:22",
        TrainType: 0,
      },
      {
        Sequence: 156,
        ArrivalTime: "20:26",
        DepartureTime: "20:26",
        TrainType: 0,
      },
      {
        Sequence: 157,
        ArrivalTime: "20:31",
        DepartureTime: "20:31",
        TrainType: 0,
      },
      {
        Sequence: 158,
        ArrivalTime: "20:38",
        DepartureTime: "20:38",
        TrainType: 0,
      },
      {
        Sequence: 159,
        ArrivalTime: "20:43",
        DepartureTime: "20:43",
        TrainType: 0,
      },
      {
        Sequence: 160,
        ArrivalTime: "20:49",
        DepartureTime: "20:49",
        TrainType: 0,
      },
      {
        Sequence: 161,
        ArrivalTime: "20:56",
        DepartureTime: "20:56",
        TrainType: 0,
      },
      {
        Sequence: 162,
        ArrivalTime: "21:02",
        DepartureTime: "21:02",
        TrainType: 0,
      },
      {
        Sequence: 163,
        ArrivalTime: "21:08",
        DepartureTime: "21:08",
        TrainType: 0,
      },
      {
        Sequence: 164,
        ArrivalTime: "21:15",
        DepartureTime: "21:15",
        TrainType: 0,
      },
      {
        Sequence: 165,
        ArrivalTime: "21:20",
        DepartureTime: "21:20",
        TrainType: 0,
      },
      {
        Sequence: 166,
        ArrivalTime: "21:27",
        DepartureTime: "21:27",
        TrainType: 0,
      },
      {
        Sequence: 167,
        ArrivalTime: "21:34",
        DepartureTime: "21:34",
        TrainType: 0,
      },
      {
        Sequence: 168,
        ArrivalTime: "21:39",
        DepartureTime: "21:39",
        TrainType: 0,
      },
      {
        Sequence: 169,
        ArrivalTime: "21:45",
        DepartureTime: "21:45",
        TrainType: 0,
      },
      {
        Sequence: 170,
        ArrivalTime: "21:53",
        DepartureTime: "21:53",
        TrainType: 0,
      },
      {
        Sequence: 171,
        ArrivalTime: "22:01",
        DepartureTime: "22:01",
        TrainType: 0,
      },
      {
        Sequence: 172,
        ArrivalTime: "22:08",
        DepartureTime: "22:08",
        TrainType: 0,
      },
      {
        Sequence: 173,
        ArrivalTime: "22:14",
        DepartureTime: "22:14",
        TrainType: 0,
      },
      {
        Sequence: 174,
        ArrivalTime: "22:21",
        DepartureTime: "22:21",
        TrainType: 0,
      },
      {
        Sequence: 175,
        ArrivalTime: "22:27",
        DepartureTime: "22:27",
        TrainType: 0,
      },
      {
        Sequence: 176,
        ArrivalTime: "22:34",
        DepartureTime: "22:34",
        TrainType: 0,
      },
      {
        Sequence: 177,
        ArrivalTime: "22:41",
        DepartureTime: "22:41",
        TrainType: 0,
      },
      {
        Sequence: 178,
        ArrivalTime: "22:50",
        DepartureTime: "22:50",
        TrainType: 0,
      },
      {
        Sequence: 179,
        ArrivalTime: "23:00",
        DepartureTime: "23:00",
        TrainType: 0,
      },
      {
        Sequence: 180,
        ArrivalTime: "23:12",
        DepartureTime: "23:12",
        TrainType: 0,
      },
      {
        Sequence: 181,
        ArrivalTime: "23:24",
        DepartureTime: "23:24",
        TrainType: 0,
      },
      {
        Sequence: 182,
        ArrivalTime: "23:36",
        DepartureTime: "23:36",
        TrainType: 0,
      },
      {
        Sequence: 183,
        ArrivalTime: "23:48",
        DepartureTime: "23:48",
        TrainType: 0,
      },
      {
        Sequence: 184,
        ArrivalTime: "00:00",
        DepartureTime: "00:00",
        TrainType: 0,
      },
    ],
    ServiceDay: {
      ServiceTag: "平日",
      Monday: true,
      Tuesday: true,
      Wednesday: true,
      Thursday: true,
      Friday: true,
      Saturday: false,
      Sunday: false,
      NationalHolidays: false,
    },
    SrcUpdateTime: "2025-11-10T00:00:00+08:00",
    UpdateTime: "2025-11-07T22:36:53+08:00",
    VersionID: 30,
  },
  {
    RouteID: "G-1",
    LineID: "G",
    StationID: "G01",
    StationName: {
      Zh_tw: "新店",
      En: "Xindian",
    },
    Direction: 0,
    DestinationStaionID: "G19",
    DestinationStationName: {
      Zh_tw: "松山",
      En: "Songshan",
    },
    Timetables: [
      {
        Sequence: 1,
        ArrivalTime: "06:00",
        DepartureTime: "06:00",
        TrainType: 0,
      },
      {
        Sequence: 2,
        ArrivalTime: "06:08",
        DepartureTime: "06:08",
        TrainType: 0,
      },
      {
        Sequence: 3,
        ArrivalTime: "06:17",
        DepartureTime: "06:17",
        TrainType: 0,
      },
      {
        Sequence: 4,
        ArrivalTime: "06:25",
        DepartureTime: "06:25",
        TrainType: 0,
      },
      {
        Sequence: 5,
        ArrivalTime: "06:31",
        DepartureTime: "06:31",
        TrainType: 0,
      },
      {
        Sequence: 6,
        ArrivalTime: "06:39",
        DepartureTime: "06:39",
        TrainType: 0,
      },
      {
        Sequence: 7,
        ArrivalTime: "06:46",
        DepartureTime: "06:46",
        TrainType: 0,
      },
      {
        Sequence: 8,
        ArrivalTime: "06:55",
        DepartureTime: "06:55",
        TrainType: 0,
      },
      {
        Sequence: 9,
        ArrivalTime: "07:04",
        DepartureTime: "07:04",
        TrainType: 0,
      },
      {
        Sequence: 10,
        ArrivalTime: "07:13",
        DepartureTime: "07:13",
        TrainType: 0,
      },
      {
        Sequence: 11,
        ArrivalTime: "07:21",
        DepartureTime: "07:21",
        TrainType: 0,
      },
      {
        Sequence: 12,
        ArrivalTime: "07:30",
        DepartureTime: "07:30",
        TrainType: 0,
      },
      {
        Sequence: 13,
        ArrivalTime: "07:36",
        DepartureTime: "07:36",
        TrainType: 0,
      },
      {
        Sequence: 14,
        ArrivalTime: "07:40",
        DepartureTime: "07:40",
        TrainType: 0,
      },
      {
        Sequence: 15,
        ArrivalTime: "07:49",
        DepartureTime: "07:49",
        TrainType: 0,
      },
      {
        Sequence: 16,
        ArrivalTime: "07:58",
        DepartureTime: "07:58",
        TrainType: 0,
      },
      {
        Sequence: 17,
        ArrivalTime: "08:06",
        DepartureTime: "08:06",
        TrainType: 0,
      },
      {
        Sequence: 18,
        ArrivalTime: "08:11",
        DepartureTime: "08:11",
        TrainType: 0,
      },
      {
        Sequence: 19,
        ArrivalTime: "08:17",
        DepartureTime: "08:17",
        TrainType: 0,
      },
      {
        Sequence: 20,
        ArrivalTime: "08:24",
        DepartureTime: "08:24",
        TrainType: 0,
      },
      {
        Sequence: 21,
        ArrivalTime: "08:31",
        DepartureTime: "08:31",
        TrainType: 0,
      },
      {
        Sequence: 22,
        ArrivalTime: "08:38",
        DepartureTime: "08:38",
        TrainType: 0,
      },
      {
        Sequence: 23,
        ArrivalTime: "08:45",
        DepartureTime: "08:45",
        TrainType: 0,
      },
      {
        Sequence: 24,
        ArrivalTime: "08:53",
        DepartureTime: "08:53",
        TrainType: 0,
      },
      {
        Sequence: 25,
        ArrivalTime: "09:00",
        DepartureTime: "09:00",
        TrainType: 0,
      },
      {
        Sequence: 26,
        ArrivalTime: "09:08",
        DepartureTime: "09:08",
        TrainType: 0,
      },
      {
        Sequence: 27,
        ArrivalTime: "09:14",
        DepartureTime: "09:14",
        TrainType: 0,
      },
      {
        Sequence: 28,
        ArrivalTime: "09:21",
        DepartureTime: "09:21",
        TrainType: 0,
      },
      {
        Sequence: 29,
        ArrivalTime: "09:29",
        DepartureTime: "09:29",
        TrainType: 0,
      },
      {
        Sequence: 30,
        ArrivalTime: "09:36",
        DepartureTime: "09:36",
        TrainType: 0,
      },
      {
        Sequence: 31,
        ArrivalTime: "09:43",
        DepartureTime: "09:43",
        TrainType: 0,
      },
      {
        Sequence: 32,
        ArrivalTime: "09:50",
        DepartureTime: "09:50",
        TrainType: 0,
      },
      {
        Sequence: 33,
        ArrivalTime: "09:57",
        DepartureTime: "09:57",
        TrainType: 0,
      },
      {
        Sequence: 34,
        ArrivalTime: "10:05",
        DepartureTime: "10:05",
        TrainType: 0,
      },
      {
        Sequence: 35,
        ArrivalTime: "10:12",
        DepartureTime: "10:12",
        TrainType: 0,
      },
      {
        Sequence: 36,
        ArrivalTime: "10:19",
        DepartureTime: "10:19",
        TrainType: 0,
      },
      {
        Sequence: 37,
        ArrivalTime: "10:26",
        DepartureTime: "10:26",
        TrainType: 0,
      },
      {
        Sequence: 38,
        ArrivalTime: "10:33",
        DepartureTime: "10:33",
        TrainType: 0,
      },
      {
        Sequence: 39,
        ArrivalTime: "10:41",
        DepartureTime: "10:41",
        TrainType: 0,
      },
      {
        Sequence: 40,
        ArrivalTime: "10:48",
        DepartureTime: "10:48",
        TrainType: 0,
      },
      {
        Sequence: 41,
        ArrivalTime: "10:55",
        DepartureTime: "10:55",
        TrainType: 0,
      },
      {
        Sequence: 42,
        ArrivalTime: "11:02",
        DepartureTime: "11:02",
        TrainType: 0,
      },
      {
        Sequence: 43,
        ArrivalTime: "11:09",
        DepartureTime: "11:09",
        TrainType: 0,
      },
      {
        Sequence: 44,
        ArrivalTime: "11:17",
        DepartureTime: "11:17",
        TrainType: 0,
      },
      {
        Sequence: 45,
        ArrivalTime: "11:24",
        DepartureTime: "11:24",
        TrainType: 0,
      },
      {
        Sequence: 46,
        ArrivalTime: "11:31",
        DepartureTime: "11:31",
        TrainType: 0,
      },
      {
        Sequence: 47,
        ArrivalTime: "11:38",
        DepartureTime: "11:38",
        TrainType: 0,
      },
      {
        Sequence: 48,
        ArrivalTime: "11:45",
        DepartureTime: "11:45",
        TrainType: 0,
      },
      {
        Sequence: 49,
        ArrivalTime: "11:53",
        DepartureTime: "11:53",
        TrainType: 0,
      },
      {
        Sequence: 50,
        ArrivalTime: "12:00",
        DepartureTime: "12:00",
        TrainType: 0,
      },
      {
        Sequence: 51,
        ArrivalTime: "12:07",
        DepartureTime: "12:07",
        TrainType: 0,
      },
      {
        Sequence: 52,
        ArrivalTime: "12:14",
        DepartureTime: "12:14",
        TrainType: 0,
      },
      {
        Sequence: 53,
        ArrivalTime: "12:21",
        DepartureTime: "12:21",
        TrainType: 0,
      },
      {
        Sequence: 54,
        ArrivalTime: "12:29",
        DepartureTime: "12:29",
        TrainType: 0,
      },
      {
        Sequence: 55,
        ArrivalTime: "12:36",
        DepartureTime: "12:36",
        TrainType: 0,
      },
      {
        Sequence: 56,
        ArrivalTime: "12:43",
        DepartureTime: "12:43",
        TrainType: 0,
      },
      {
        Sequence: 57,
        ArrivalTime: "12:50",
        DepartureTime: "12:50",
        TrainType: 0,
      },
      {
        Sequence: 58,
        ArrivalTime: "12:57",
        DepartureTime: "12:57",
        TrainType: 0,
      },
      {
        Sequence: 59,
        ArrivalTime: "13:05",
        DepartureTime: "13:05",
        TrainType: 0,
      },
      {
        Sequence: 60,
        ArrivalTime: "13:12",
        DepartureTime: "13:12",
        TrainType: 0,
      },
      {
        Sequence: 61,
        ArrivalTime: "13:19",
        DepartureTime: "13:19",
        TrainType: 0,
      },
      {
        Sequence: 62,
        ArrivalTime: "13:26",
        DepartureTime: "13:26",
        TrainType: 0,
      },
      {
        Sequence: 63,
        ArrivalTime: "13:33",
        DepartureTime: "13:33",
        TrainType: 0,
      },
      {
        Sequence: 64,
        ArrivalTime: "13:41",
        DepartureTime: "13:41",
        TrainType: 0,
      },
      {
        Sequence: 65,
        ArrivalTime: "13:48",
        DepartureTime: "13:48",
        TrainType: 0,
      },
      {
        Sequence: 66,
        ArrivalTime: "13:55",
        DepartureTime: "13:55",
        TrainType: 0,
      },
      {
        Sequence: 67,
        ArrivalTime: "14:02",
        DepartureTime: "14:02",
        TrainType: 0,
      },
      {
        Sequence: 68,
        ArrivalTime: "14:09",
        DepartureTime: "14:09",
        TrainType: 0,
      },
      {
        Sequence: 69,
        ArrivalTime: "14:17",
        DepartureTime: "14:17",
        TrainType: 0,
      },
      {
        Sequence: 70,
        ArrivalTime: "14:24",
        DepartureTime: "14:24",
        TrainType: 0,
      },
      {
        Sequence: 71,
        ArrivalTime: "14:31",
        DepartureTime: "14:31",
        TrainType: 0,
      },
      {
        Sequence: 72,
        ArrivalTime: "14:38",
        DepartureTime: "14:38",
        TrainType: 0,
      },
      {
        Sequence: 73,
        ArrivalTime: "14:45",
        DepartureTime: "14:45",
        TrainType: 0,
      },
      {
        Sequence: 74,
        ArrivalTime: "14:53",
        DepartureTime: "14:53",
        TrainType: 0,
      },
      {
        Sequence: 75,
        ArrivalTime: "15:00",
        DepartureTime: "15:00",
        TrainType: 0,
      },
      {
        Sequence: 76,
        ArrivalTime: "15:07",
        DepartureTime: "15:07",
        TrainType: 0,
      },
      {
        Sequence: 77,
        ArrivalTime: "15:14",
        DepartureTime: "15:14",
        TrainType: 0,
      },
      {
        Sequence: 78,
        ArrivalTime: "15:21",
        DepartureTime: "15:21",
        TrainType: 0,
      },
      {
        Sequence: 79,
        ArrivalTime: "15:29",
        DepartureTime: "15:29",
        TrainType: 0,
      },
      {
        Sequence: 80,
        ArrivalTime: "15:36",
        DepartureTime: "15:36",
        TrainType: 0,
      },
      {
        Sequence: 81,
        ArrivalTime: "15:43",
        DepartureTime: "15:43",
        TrainType: 0,
      },
      {
        Sequence: 82,
        ArrivalTime: "15:50",
        DepartureTime: "15:50",
        TrainType: 0,
      },
      {
        Sequence: 83,
        ArrivalTime: "15:57",
        DepartureTime: "15:57",
        TrainType: 0,
      },
      {
        Sequence: 84,
        ArrivalTime: "16:05",
        DepartureTime: "16:05",
        TrainType: 0,
      },
      {
        Sequence: 85,
        ArrivalTime: "16:12",
        DepartureTime: "16:12",
        TrainType: 0,
      },
      {
        Sequence: 86,
        ArrivalTime: "16:19",
        DepartureTime: "16:19",
        TrainType: 0,
      },
      {
        Sequence: 87,
        ArrivalTime: "16:25",
        DepartureTime: "16:25",
        TrainType: 0,
      },
      {
        Sequence: 88,
        ArrivalTime: "16:31",
        DepartureTime: "16:31",
        TrainType: 0,
      },
      {
        Sequence: 89,
        ArrivalTime: "16:37",
        DepartureTime: "16:37",
        TrainType: 0,
      },
      {
        Sequence: 90,
        ArrivalTime: "16:43",
        DepartureTime: "16:43",
        TrainType: 0,
      },
      {
        Sequence: 91,
        ArrivalTime: "16:49",
        DepartureTime: "16:49",
        TrainType: 0,
      },
      {
        Sequence: 92,
        ArrivalTime: "16:55",
        DepartureTime: "16:55",
        TrainType: 0,
      },
      {
        Sequence: 93,
        ArrivalTime: "17:01",
        DepartureTime: "17:01",
        TrainType: 0,
      },
      {
        Sequence: 94,
        ArrivalTime: "17:07",
        DepartureTime: "17:07",
        TrainType: 0,
      },
      {
        Sequence: 95,
        ArrivalTime: "17:13",
        DepartureTime: "17:13",
        TrainType: 0,
      },
      {
        Sequence: 96,
        ArrivalTime: "17:19",
        DepartureTime: "17:19",
        TrainType: 0,
      },
      {
        Sequence: 97,
        ArrivalTime: "17:25",
        DepartureTime: "17:25",
        TrainType: 0,
      },
      {
        Sequence: 98,
        ArrivalTime: "17:31",
        DepartureTime: "17:31",
        TrainType: 0,
      },
      {
        Sequence: 99,
        ArrivalTime: "17:37",
        DepartureTime: "17:37",
        TrainType: 0,
      },
      {
        Sequence: 100,
        ArrivalTime: "17:43",
        DepartureTime: "17:43",
        TrainType: 0,
      },
      {
        Sequence: 101,
        ArrivalTime: "17:49",
        DepartureTime: "17:49",
        TrainType: 0,
      },
      {
        Sequence: 102,
        ArrivalTime: "17:55",
        DepartureTime: "17:55",
        TrainType: 0,
      },
      {
        Sequence: 103,
        ArrivalTime: "18:01",
        DepartureTime: "18:01",
        TrainType: 0,
      },
      {
        Sequence: 104,
        ArrivalTime: "18:07",
        DepartureTime: "18:07",
        TrainType: 0,
      },
      {
        Sequence: 105,
        ArrivalTime: "18:13",
        DepartureTime: "18:13",
        TrainType: 0,
      },
      {
        Sequence: 106,
        ArrivalTime: "18:19",
        DepartureTime: "18:19",
        TrainType: 0,
      },
      {
        Sequence: 107,
        ArrivalTime: "18:25",
        DepartureTime: "18:25",
        TrainType: 0,
      },
      {
        Sequence: 108,
        ArrivalTime: "18:31",
        DepartureTime: "18:31",
        TrainType: 0,
      },
      {
        Sequence: 109,
        ArrivalTime: "18:37",
        DepartureTime: "18:37",
        TrainType: 0,
      },
      {
        Sequence: 110,
        ArrivalTime: "18:43",
        DepartureTime: "18:43",
        TrainType: 0,
      },
      {
        Sequence: 111,
        ArrivalTime: "18:49",
        DepartureTime: "18:49",
        TrainType: 0,
      },
      {
        Sequence: 112,
        ArrivalTime: "18:55",
        DepartureTime: "18:55",
        TrainType: 0,
      },
      {
        Sequence: 113,
        ArrivalTime: "19:01",
        DepartureTime: "19:01",
        TrainType: 0,
      },
      {
        Sequence: 114,
        ArrivalTime: "19:07",
        DepartureTime: "19:07",
        TrainType: 0,
      },
      {
        Sequence: 115,
        ArrivalTime: "19:13",
        DepartureTime: "19:13",
        TrainType: 0,
      },
      {
        Sequence: 116,
        ArrivalTime: "19:19",
        DepartureTime: "19:19",
        TrainType: 0,
      },
      {
        Sequence: 117,
        ArrivalTime: "19:26",
        DepartureTime: "19:26",
        TrainType: 0,
      },
      {
        Sequence: 118,
        ArrivalTime: "19:33",
        DepartureTime: "19:33",
        TrainType: 0,
      },
      {
        Sequence: 119,
        ArrivalTime: "19:41",
        DepartureTime: "19:41",
        TrainType: 0,
      },
      {
        Sequence: 120,
        ArrivalTime: "19:48",
        DepartureTime: "19:48",
        TrainType: 0,
      },
      {
        Sequence: 121,
        ArrivalTime: "19:55",
        DepartureTime: "19:55",
        TrainType: 0,
      },
      {
        Sequence: 122,
        ArrivalTime: "20:02",
        DepartureTime: "20:02",
        TrainType: 0,
      },
      {
        Sequence: 123,
        ArrivalTime: "20:09",
        DepartureTime: "20:09",
        TrainType: 0,
      },
      {
        Sequence: 124,
        ArrivalTime: "20:17",
        DepartureTime: "20:17",
        TrainType: 0,
      },
      {
        Sequence: 125,
        ArrivalTime: "20:24",
        DepartureTime: "20:24",
        TrainType: 0,
      },
      {
        Sequence: 126,
        ArrivalTime: "20:31",
        DepartureTime: "20:31",
        TrainType: 0,
      },
      {
        Sequence: 127,
        ArrivalTime: "20:38",
        DepartureTime: "20:38",
        TrainType: 0,
      },
      {
        Sequence: 128,
        ArrivalTime: "20:45",
        DepartureTime: "20:45",
        TrainType: 0,
      },
      {
        Sequence: 129,
        ArrivalTime: "20:53",
        DepartureTime: "20:53",
        TrainType: 0,
      },
      {
        Sequence: 130,
        ArrivalTime: "21:00",
        DepartureTime: "21:00",
        TrainType: 0,
      },
      {
        Sequence: 131,
        ArrivalTime: "21:07",
        DepartureTime: "21:07",
        TrainType: 0,
      },
      {
        Sequence: 132,
        ArrivalTime: "21:14",
        DepartureTime: "21:14",
        TrainType: 0,
      },
      {
        Sequence: 133,
        ArrivalTime: "21:21",
        DepartureTime: "21:21",
        TrainType: 0,
      },
      {
        Sequence: 134,
        ArrivalTime: "21:29",
        DepartureTime: "21:29",
        TrainType: 0,
      },
      {
        Sequence: 135,
        ArrivalTime: "21:36",
        DepartureTime: "21:36",
        TrainType: 0,
      },
      {
        Sequence: 136,
        ArrivalTime: "21:43",
        DepartureTime: "21:43",
        TrainType: 0,
      },
      {
        Sequence: 137,
        ArrivalTime: "21:50",
        DepartureTime: "21:50",
        TrainType: 0,
      },
      {
        Sequence: 138,
        ArrivalTime: "21:58",
        DepartureTime: "21:58",
        TrainType: 0,
      },
      {
        Sequence: 139,
        ArrivalTime: "22:06",
        DepartureTime: "22:06",
        TrainType: 0,
      },
      {
        Sequence: 140,
        ArrivalTime: "22:14",
        DepartureTime: "22:14",
        TrainType: 0,
      },
      {
        Sequence: 141,
        ArrivalTime: "22:20",
        DepartureTime: "22:20",
        TrainType: 0,
      },
      {
        Sequence: 142,
        ArrivalTime: "22:27",
        DepartureTime: "22:27",
        TrainType: 0,
      },
      {
        Sequence: 143,
        ArrivalTime: "22:34",
        DepartureTime: "22:34",
        TrainType: 0,
      },
      {
        Sequence: 144,
        ArrivalTime: "22:41",
        DepartureTime: "22:41",
        TrainType: 0,
      },
      {
        Sequence: 145,
        ArrivalTime: "22:49",
        DepartureTime: "22:49",
        TrainType: 0,
      },
      {
        Sequence: 146,
        ArrivalTime: "23:00",
        DepartureTime: "23:00",
        TrainType: 0,
      },
      {
        Sequence: 147,
        ArrivalTime: "23:12",
        DepartureTime: "23:12",
        TrainType: 0,
      },
      {
        Sequence: 148,
        ArrivalTime: "23:24",
        DepartureTime: "23:24",
        TrainType: 0,
      },
      {
        Sequence: 149,
        ArrivalTime: "23:36",
        DepartureTime: "23:36",
        TrainType: 0,
      },
      {
        Sequence: 150,
        ArrivalTime: "23:48",
        DepartureTime: "23:48",
        TrainType: 0,
      },
      {
        Sequence: 151,
        ArrivalTime: "00:00",
        DepartureTime: "00:00",
        TrainType: 0,
      },
    ],
    ServiceDay: {
      ServiceTag: "假日",
      Monday: false,
      Tuesday: false,
      Wednesday: false,
      Thursday: false,
      Friday: false,
      Saturday: true,
      Sunday: true,
      NationalHolidays: true,
    },
    SrcUpdateTime: "2025-11-10T00:00:00+08:00",
    UpdateTime: "2025-11-07T22:36:53+08:00",
    VersionID: 30,
  },
  {
    RouteID: "G-1",
    LineID: "G",
    StationID: "G19",
    StationName: {
      Zh_tw: "松山",
      En: "Songshan",
    },
    Direction: 1,
    DestinationStaionID: "G01",
    DestinationStationName: {
      Zh_tw: "新店",
      En: "Xindian",
    },
    Timetables: [
      {
        Sequence: 1,
        ArrivalTime: "06:00",
        DepartureTime: "06:00",
        TrainType: 0,
      },
      {
        Sequence: 2,
        ArrivalTime: "06:05",
        DepartureTime: "06:05",
        TrainType: 0,
      },
      {
        Sequence: 3,
        ArrivalTime: "06:14",
        DepartureTime: "06:14",
        TrainType: 0,
      },
      {
        Sequence: 4,
        ArrivalTime: "06:21",
        DepartureTime: "06:21",
        TrainType: 0,
      },
      {
        Sequence: 5,
        ArrivalTime: "06:28",
        DepartureTime: "06:28",
        TrainType: 0,
      },
      {
        Sequence: 6,
        ArrivalTime: "06:38",
        DepartureTime: "06:38",
        TrainType: 0,
      },
      {
        Sequence: 7,
        ArrivalTime: "06:47",
        DepartureTime: "06:47",
        TrainType: 0,
      },
      {
        Sequence: 8,
        ArrivalTime: "06:57",
        DepartureTime: "06:57",
        TrainType: 0,
      },
      {
        Sequence: 9,
        ArrivalTime: "07:01",
        DepartureTime: "07:01",
        TrainType: 0,
      },
      {
        Sequence: 10,
        ArrivalTime: "07:09",
        DepartureTime: "07:09",
        TrainType: 0,
      },
      {
        Sequence: 11,
        ArrivalTime: "07:16",
        DepartureTime: "07:16",
        TrainType: 0,
      },
      {
        Sequence: 12,
        ArrivalTime: "07:24",
        DepartureTime: "07:24",
        TrainType: 0,
      },
      {
        Sequence: 13,
        ArrivalTime: "07:32",
        DepartureTime: "07:32",
        TrainType: 0,
      },
      {
        Sequence: 14,
        ArrivalTime: "07:38",
        DepartureTime: "07:38",
        TrainType: 0,
      },
      {
        Sequence: 15,
        ArrivalTime: "07:44",
        DepartureTime: "07:44",
        TrainType: 0,
      },
      {
        Sequence: 16,
        ArrivalTime: "07:51",
        DepartureTime: "07:51",
        TrainType: 0,
      },
      {
        Sequence: 17,
        ArrivalTime: "07:59",
        DepartureTime: "07:59",
        TrainType: 0,
      },
      {
        Sequence: 18,
        ArrivalTime: "08:06",
        DepartureTime: "08:06",
        TrainType: 0,
      },
      {
        Sequence: 19,
        ArrivalTime: "08:13",
        DepartureTime: "08:13",
        TrainType: 0,
      },
      {
        Sequence: 20,
        ArrivalTime: "08:20",
        DepartureTime: "08:20",
        TrainType: 0,
      },
      {
        Sequence: 21,
        ArrivalTime: "08:26",
        DepartureTime: "08:26",
        TrainType: 0,
      },
      {
        Sequence: 22,
        ArrivalTime: "08:30",
        DepartureTime: "08:30",
        TrainType: 0,
      },
      {
        Sequence: 23,
        ArrivalTime: "08:35",
        DepartureTime: "08:35",
        TrainType: 0,
      },
      {
        Sequence: 24,
        ArrivalTime: "08:42",
        DepartureTime: "08:42",
        TrainType: 0,
      },
      {
        Sequence: 25,
        ArrivalTime: "08:49",
        DepartureTime: "08:49",
        TrainType: 0,
      },
      {
        Sequence: 26,
        ArrivalTime: "08:56",
        DepartureTime: "08:56",
        TrainType: 0,
      },
      {
        Sequence: 27,
        ArrivalTime: "09:03",
        DepartureTime: "09:03",
        TrainType: 0,
      },
      {
        Sequence: 28,
        ArrivalTime: "09:11",
        DepartureTime: "09:11",
        TrainType: 0,
      },
      {
        Sequence: 29,
        ArrivalTime: "09:18",
        DepartureTime: "09:18",
        TrainType: 0,
      },
      {
        Sequence: 30,
        ArrivalTime: "09:25",
        DepartureTime: "09:25",
        TrainType: 0,
      },
      {
        Sequence: 31,
        ArrivalTime: "09:32",
        DepartureTime: "09:32",
        TrainType: 0,
      },
      {
        Sequence: 32,
        ArrivalTime: "09:39",
        DepartureTime: "09:39",
        TrainType: 0,
      },
      {
        Sequence: 33,
        ArrivalTime: "09:47",
        DepartureTime: "09:47",
        TrainType: 0,
      },
      {
        Sequence: 34,
        ArrivalTime: "09:54",
        DepartureTime: "09:54",
        TrainType: 0,
      },
      {
        Sequence: 35,
        ArrivalTime: "10:01",
        DepartureTime: "10:01",
        TrainType: 0,
      },
      {
        Sequence: 36,
        ArrivalTime: "10:08",
        DepartureTime: "10:08",
        TrainType: 0,
      },
      {
        Sequence: 37,
        ArrivalTime: "10:15",
        DepartureTime: "10:15",
        TrainType: 0,
      },
      {
        Sequence: 38,
        ArrivalTime: "10:23",
        DepartureTime: "10:23",
        TrainType: 0,
      },
      {
        Sequence: 39,
        ArrivalTime: "10:30",
        DepartureTime: "10:30",
        TrainType: 0,
      },
      {
        Sequence: 40,
        ArrivalTime: "10:37",
        DepartureTime: "10:37",
        TrainType: 0,
      },
      {
        Sequence: 41,
        ArrivalTime: "10:44",
        DepartureTime: "10:44",
        TrainType: 0,
      },
      {
        Sequence: 42,
        ArrivalTime: "10:51",
        DepartureTime: "10:51",
        TrainType: 0,
      },
      {
        Sequence: 43,
        ArrivalTime: "10:59",
        DepartureTime: "10:59",
        TrainType: 0,
      },
      {
        Sequence: 44,
        ArrivalTime: "11:06",
        DepartureTime: "11:06",
        TrainType: 0,
      },
      {
        Sequence: 45,
        ArrivalTime: "11:13",
        DepartureTime: "11:13",
        TrainType: 0,
      },
      {
        Sequence: 46,
        ArrivalTime: "11:20",
        DepartureTime: "11:20",
        TrainType: 0,
      },
      {
        Sequence: 47,
        ArrivalTime: "11:27",
        DepartureTime: "11:27",
        TrainType: 0,
      },
      {
        Sequence: 48,
        ArrivalTime: "11:35",
        DepartureTime: "11:35",
        TrainType: 0,
      },
      {
        Sequence: 49,
        ArrivalTime: "11:42",
        DepartureTime: "11:42",
        TrainType: 0,
      },
      {
        Sequence: 50,
        ArrivalTime: "11:49",
        DepartureTime: "11:49",
        TrainType: 0,
      },
      {
        Sequence: 51,
        ArrivalTime: "11:56",
        DepartureTime: "11:56",
        TrainType: 0,
      },
      {
        Sequence: 52,
        ArrivalTime: "12:03",
        DepartureTime: "12:03",
        TrainType: 0,
      },
      {
        Sequence: 53,
        ArrivalTime: "12:11",
        DepartureTime: "12:11",
        TrainType: 0,
      },
      {
        Sequence: 54,
        ArrivalTime: "12:18",
        DepartureTime: "12:18",
        TrainType: 0,
      },
      {
        Sequence: 55,
        ArrivalTime: "12:25",
        DepartureTime: "12:25",
        TrainType: 0,
      },
      {
        Sequence: 56,
        ArrivalTime: "12:32",
        DepartureTime: "12:32",
        TrainType: 0,
      },
      {
        Sequence: 57,
        ArrivalTime: "12:39",
        DepartureTime: "12:39",
        TrainType: 0,
      },
      {
        Sequence: 58,
        ArrivalTime: "12:47",
        DepartureTime: "12:47",
        TrainType: 0,
      },
      {
        Sequence: 59,
        ArrivalTime: "12:54",
        DepartureTime: "12:54",
        TrainType: 0,
      },
      {
        Sequence: 60,
        ArrivalTime: "13:01",
        DepartureTime: "13:01",
        TrainType: 0,
      },
      {
        Sequence: 61,
        ArrivalTime: "13:08",
        DepartureTime: "13:08",
        TrainType: 0,
      },
      {
        Sequence: 62,
        ArrivalTime: "13:15",
        DepartureTime: "13:15",
        TrainType: 0,
      },
      {
        Sequence: 63,
        ArrivalTime: "13:23",
        DepartureTime: "13:23",
        TrainType: 0,
      },
      {
        Sequence: 64,
        ArrivalTime: "13:30",
        DepartureTime: "13:30",
        TrainType: 0,
      },
      {
        Sequence: 65,
        ArrivalTime: "13:37",
        DepartureTime: "13:37",
        TrainType: 0,
      },
      {
        Sequence: 66,
        ArrivalTime: "13:44",
        DepartureTime: "13:44",
        TrainType: 0,
      },
      {
        Sequence: 67,
        ArrivalTime: "13:51",
        DepartureTime: "13:51",
        TrainType: 0,
      },
      {
        Sequence: 68,
        ArrivalTime: "13:59",
        DepartureTime: "13:59",
        TrainType: 0,
      },
      {
        Sequence: 69,
        ArrivalTime: "14:06",
        DepartureTime: "14:06",
        TrainType: 0,
      },
      {
        Sequence: 70,
        ArrivalTime: "14:13",
        DepartureTime: "14:13",
        TrainType: 0,
      },
      {
        Sequence: 71,
        ArrivalTime: "14:20",
        DepartureTime: "14:20",
        TrainType: 0,
      },
      {
        Sequence: 72,
        ArrivalTime: "14:27",
        DepartureTime: "14:27",
        TrainType: 0,
      },
      {
        Sequence: 73,
        ArrivalTime: "14:35",
        DepartureTime: "14:35",
        TrainType: 0,
      },
      {
        Sequence: 74,
        ArrivalTime: "14:42",
        DepartureTime: "14:42",
        TrainType: 0,
      },
      {
        Sequence: 75,
        ArrivalTime: "14:49",
        DepartureTime: "14:49",
        TrainType: 0,
      },
      {
        Sequence: 76,
        ArrivalTime: "14:56",
        DepartureTime: "14:56",
        TrainType: 0,
      },
      {
        Sequence: 77,
        ArrivalTime: "15:03",
        DepartureTime: "15:03",
        TrainType: 0,
      },
      {
        Sequence: 78,
        ArrivalTime: "15:11",
        DepartureTime: "15:11",
        TrainType: 0,
      },
      {
        Sequence: 79,
        ArrivalTime: "15:18",
        DepartureTime: "15:18",
        TrainType: 0,
      },
      {
        Sequence: 80,
        ArrivalTime: "15:25",
        DepartureTime: "15:25",
        TrainType: 0,
      },
      {
        Sequence: 81,
        ArrivalTime: "15:32",
        DepartureTime: "15:32",
        TrainType: 0,
      },
      {
        Sequence: 82,
        ArrivalTime: "15:39",
        DepartureTime: "15:39",
        TrainType: 0,
      },
      {
        Sequence: 83,
        ArrivalTime: "15:45",
        DepartureTime: "15:45",
        TrainType: 0,
      },
      {
        Sequence: 84,
        ArrivalTime: "15:51",
        DepartureTime: "15:51",
        TrainType: 0,
      },
      {
        Sequence: 85,
        ArrivalTime: "15:57",
        DepartureTime: "15:57",
        TrainType: 0,
      },
      {
        Sequence: 86,
        ArrivalTime: "16:03",
        DepartureTime: "16:03",
        TrainType: 0,
      },
      {
        Sequence: 87,
        ArrivalTime: "16:09",
        DepartureTime: "16:09",
        TrainType: 0,
      },
      {
        Sequence: 88,
        ArrivalTime: "16:15",
        DepartureTime: "16:15",
        TrainType: 0,
      },
      {
        Sequence: 89,
        ArrivalTime: "16:21",
        DepartureTime: "16:21",
        TrainType: 0,
      },
      {
        Sequence: 90,
        ArrivalTime: "16:27",
        DepartureTime: "16:27",
        TrainType: 0,
      },
      {
        Sequence: 91,
        ArrivalTime: "16:33",
        DepartureTime: "16:33",
        TrainType: 0,
      },
      {
        Sequence: 92,
        ArrivalTime: "16:39",
        DepartureTime: "16:39",
        TrainType: 0,
      },
      {
        Sequence: 93,
        ArrivalTime: "16:45",
        DepartureTime: "16:45",
        TrainType: 0,
      },
      {
        Sequence: 94,
        ArrivalTime: "16:51",
        DepartureTime: "16:51",
        TrainType: 0,
      },
      {
        Sequence: 95,
        ArrivalTime: "16:57",
        DepartureTime: "16:57",
        TrainType: 0,
      },
      {
        Sequence: 96,
        ArrivalTime: "17:03",
        DepartureTime: "17:03",
        TrainType: 0,
      },
      {
        Sequence: 97,
        ArrivalTime: "17:09",
        DepartureTime: "17:09",
        TrainType: 0,
      },
      {
        Sequence: 98,
        ArrivalTime: "17:15",
        DepartureTime: "17:15",
        TrainType: 0,
      },
      {
        Sequence: 99,
        ArrivalTime: "17:21",
        DepartureTime: "17:21",
        TrainType: 0,
      },
      {
        Sequence: 100,
        ArrivalTime: "17:27",
        DepartureTime: "17:27",
        TrainType: 0,
      },
      {
        Sequence: 101,
        ArrivalTime: "17:33",
        DepartureTime: "17:33",
        TrainType: 0,
      },
      {
        Sequence: 102,
        ArrivalTime: "17:39",
        DepartureTime: "17:39",
        TrainType: 0,
      },
      {
        Sequence: 103,
        ArrivalTime: "17:45",
        DepartureTime: "17:45",
        TrainType: 0,
      },
      {
        Sequence: 104,
        ArrivalTime: "17:51",
        DepartureTime: "17:51",
        TrainType: 0,
      },
      {
        Sequence: 105,
        ArrivalTime: "17:57",
        DepartureTime: "17:57",
        TrainType: 0,
      },
      {
        Sequence: 106,
        ArrivalTime: "18:03",
        DepartureTime: "18:03",
        TrainType: 0,
      },
      {
        Sequence: 107,
        ArrivalTime: "18:09",
        DepartureTime: "18:09",
        TrainType: 0,
      },
      {
        Sequence: 108,
        ArrivalTime: "18:15",
        DepartureTime: "18:15",
        TrainType: 0,
      },
      {
        Sequence: 109,
        ArrivalTime: "18:21",
        DepartureTime: "18:21",
        TrainType: 0,
      },
      {
        Sequence: 110,
        ArrivalTime: "18:27",
        DepartureTime: "18:27",
        TrainType: 0,
      },
      {
        Sequence: 111,
        ArrivalTime: "18:33",
        DepartureTime: "18:33",
        TrainType: 0,
      },
      {
        Sequence: 112,
        ArrivalTime: "18:40",
        DepartureTime: "18:40",
        TrainType: 0,
      },
      {
        Sequence: 113,
        ArrivalTime: "18:47",
        DepartureTime: "18:47",
        TrainType: 0,
      },
      {
        Sequence: 114,
        ArrivalTime: "18:54",
        DepartureTime: "18:54",
        TrainType: 0,
      },
      {
        Sequence: 115,
        ArrivalTime: "19:01",
        DepartureTime: "19:01",
        TrainType: 0,
      },
      {
        Sequence: 116,
        ArrivalTime: "19:09",
        DepartureTime: "19:09",
        TrainType: 0,
      },
      {
        Sequence: 117,
        ArrivalTime: "19:16",
        DepartureTime: "19:16",
        TrainType: 0,
      },
      {
        Sequence: 118,
        ArrivalTime: "19:23",
        DepartureTime: "19:23",
        TrainType: 0,
      },
      {
        Sequence: 119,
        ArrivalTime: "19:30",
        DepartureTime: "19:30",
        TrainType: 0,
      },
      {
        Sequence: 120,
        ArrivalTime: "19:37",
        DepartureTime: "19:37",
        TrainType: 0,
      },
      {
        Sequence: 121,
        ArrivalTime: "19:45",
        DepartureTime: "19:45",
        TrainType: 0,
      },
      {
        Sequence: 122,
        ArrivalTime: "19:52",
        DepartureTime: "19:52",
        TrainType: 0,
      },
      {
        Sequence: 123,
        ArrivalTime: "19:59",
        DepartureTime: "19:59",
        TrainType: 0,
      },
      {
        Sequence: 124,
        ArrivalTime: "20:06",
        DepartureTime: "20:06",
        TrainType: 0,
      },
      {
        Sequence: 125,
        ArrivalTime: "20:13",
        DepartureTime: "20:13",
        TrainType: 0,
      },
      {
        Sequence: 126,
        ArrivalTime: "20:21",
        DepartureTime: "20:21",
        TrainType: 0,
      },
      {
        Sequence: 127,
        ArrivalTime: "20:28",
        DepartureTime: "20:28",
        TrainType: 0,
      },
      {
        Sequence: 128,
        ArrivalTime: "20:35",
        DepartureTime: "20:35",
        TrainType: 0,
      },
      {
        Sequence: 129,
        ArrivalTime: "20:42",
        DepartureTime: "20:42",
        TrainType: 0,
      },
      {
        Sequence: 130,
        ArrivalTime: "20:49",
        DepartureTime: "20:49",
        TrainType: 0,
      },
      {
        Sequence: 131,
        ArrivalTime: "20:57",
        DepartureTime: "20:57",
        TrainType: 0,
      },
      {
        Sequence: 132,
        ArrivalTime: "21:04",
        DepartureTime: "21:04",
        TrainType: 0,
      },
      {
        Sequence: 133,
        ArrivalTime: "21:11",
        DepartureTime: "21:11",
        TrainType: 0,
      },
      {
        Sequence: 134,
        ArrivalTime: "21:18",
        DepartureTime: "21:18",
        TrainType: 0,
      },
      {
        Sequence: 135,
        ArrivalTime: "21:25",
        DepartureTime: "21:25",
        TrainType: 0,
      },
      {
        Sequence: 136,
        ArrivalTime: "21:33",
        DepartureTime: "21:33",
        TrainType: 0,
      },
      {
        Sequence: 137,
        ArrivalTime: "21:40",
        DepartureTime: "21:40",
        TrainType: 0,
      },
      {
        Sequence: 138,
        ArrivalTime: "21:47",
        DepartureTime: "21:47",
        TrainType: 0,
      },
      {
        Sequence: 139,
        ArrivalTime: "21:54",
        DepartureTime: "21:54",
        TrainType: 0,
      },
      {
        Sequence: 140,
        ArrivalTime: "22:01",
        DepartureTime: "22:01",
        TrainType: 0,
      },
      {
        Sequence: 141,
        ArrivalTime: "22:08",
        DepartureTime: "22:08",
        TrainType: 0,
      },
      {
        Sequence: 142,
        ArrivalTime: "22:14",
        DepartureTime: "22:14",
        TrainType: 0,
      },
      {
        Sequence: 143,
        ArrivalTime: "22:21",
        DepartureTime: "22:21",
        TrainType: 0,
      },
      {
        Sequence: 144,
        ArrivalTime: "22:27",
        DepartureTime: "22:27",
        TrainType: 0,
      },
      {
        Sequence: 145,
        ArrivalTime: "22:34",
        DepartureTime: "22:34",
        TrainType: 0,
      },
      {
        Sequence: 146,
        ArrivalTime: "22:40",
        DepartureTime: "22:40",
        TrainType: 0,
      },
      {
        Sequence: 147,
        ArrivalTime: "22:47",
        DepartureTime: "22:47",
        TrainType: 0,
      },
      {
        Sequence: 148,
        ArrivalTime: "22:53",
        DepartureTime: "22:53",
        TrainType: 0,
      },
      {
        Sequence: 149,
        ArrivalTime: "23:00",
        DepartureTime: "23:00",
        TrainType: 0,
      },
      {
        Sequence: 150,
        ArrivalTime: "23:08",
        DepartureTime: "23:08",
        TrainType: 0,
      },
      {
        Sequence: 151,
        ArrivalTime: "23:18",
        DepartureTime: "23:18",
        TrainType: 0,
      },
      {
        Sequence: 152,
        ArrivalTime: "23:24",
        DepartureTime: "23:24",
        TrainType: 0,
      },
      {
        Sequence: 153,
        ArrivalTime: "23:36",
        DepartureTime: "23:36",
        TrainType: 0,
      },
      {
        Sequence: 154,
        ArrivalTime: "23:48",
        DepartureTime: "23:48",
        TrainType: 0,
      },
      {
        Sequence: 155,
        ArrivalTime: "00:00",
        DepartureTime: "00:00",
        TrainType: 0,
      },
    ],
    ServiceDay: {
      ServiceTag: "假日",
      Monday: false,
      Tuesday: false,
      Wednesday: false,
      Thursday: false,
      Friday: false,
      Saturday: true,
      Sunday: true,
      NationalHolidays: true,
    },
    SrcUpdateTime: "2025-11-10T00:00:00+08:00",
    UpdateTime: "2025-11-07T22:36:53+08:00",
    VersionID: 30,
  },
  {
    RouteID: "G-1",
    LineID: "G",
    StationID: "G19",
    StationName: {
      Zh_tw: "松山",
      En: "Songshan",
    },
    Direction: 1,
    DestinationStaionID: "G01",
    DestinationStationName: {
      Zh_tw: "新店",
      En: "Xindian",
    },
    Timetables: [
      {
        Sequence: 1,
        ArrivalTime: "06:00",
        DepartureTime: "06:00",
        TrainType: 0,
      },
      {
        Sequence: 2,
        ArrivalTime: "06:05",
        DepartureTime: "06:05",
        TrainType: 0,
      },
      {
        Sequence: 3,
        ArrivalTime: "06:14",
        DepartureTime: "06:14",
        TrainType: 0,
      },
      {
        Sequence: 4,
        ArrivalTime: "06:22",
        DepartureTime: "06:22",
        TrainType: 0,
      },
      {
        Sequence: 5,
        ArrivalTime: "06:27",
        DepartureTime: "06:27",
        TrainType: 0,
      },
      {
        Sequence: 6,
        ArrivalTime: "06:32",
        DepartureTime: "06:32",
        TrainType: 0,
      },
      {
        Sequence: 7,
        ArrivalTime: "06:39",
        DepartureTime: "06:39",
        TrainType: 0,
      },
      {
        Sequence: 8,
        ArrivalTime: "06:43",
        DepartureTime: "06:43",
        TrainType: 0,
      },
      {
        Sequence: 9,
        ArrivalTime: "06:45",
        DepartureTime: "06:45",
        TrainType: 0,
      },
      {
        Sequence: 10,
        ArrivalTime: "06:52",
        DepartureTime: "06:52",
        TrainType: 0,
      },
      {
        Sequence: 11,
        ArrivalTime: "06:54",
        DepartureTime: "06:54",
        TrainType: 0,
      },
      {
        Sequence: 12,
        ArrivalTime: "06:57",
        DepartureTime: "06:57",
        TrainType: 0,
      },
      {
        Sequence: 13,
        ArrivalTime: "07:04",
        DepartureTime: "07:04",
        TrainType: 0,
      },
      {
        Sequence: 14,
        ArrivalTime: "07:07",
        DepartureTime: "07:07",
        TrainType: 0,
      },
      {
        Sequence: 15,
        ArrivalTime: "07:10",
        DepartureTime: "07:10",
        TrainType: 0,
      },
      {
        Sequence: 16,
        ArrivalTime: "07:16",
        DepartureTime: "07:16",
        TrainType: 0,
      },
      {
        Sequence: 17,
        ArrivalTime: "07:19",
        DepartureTime: "07:19",
        TrainType: 0,
      },
      {
        Sequence: 18,
        ArrivalTime: "07:22",
        DepartureTime: "07:22",
        TrainType: 0,
      },
      {
        Sequence: 19,
        ArrivalTime: "07:28",
        DepartureTime: "07:28",
        TrainType: 0,
      },
      {
        Sequence: 20,
        ArrivalTime: "07:31",
        DepartureTime: "07:31",
        TrainType: 0,
      },
      {
        Sequence: 21,
        ArrivalTime: "07:34",
        DepartureTime: "07:34",
        TrainType: 0,
      },
      {
        Sequence: 22,
        ArrivalTime: "07:40",
        DepartureTime: "07:40",
        TrainType: 0,
      },
      {
        Sequence: 23,
        ArrivalTime: "07:43",
        DepartureTime: "07:43",
        TrainType: 0,
      },
      {
        Sequence: 24,
        ArrivalTime: "07:46",
        DepartureTime: "07:46",
        TrainType: 0,
      },
      {
        Sequence: 25,
        ArrivalTime: "07:52",
        DepartureTime: "07:52",
        TrainType: 0,
      },
      {
        Sequence: 26,
        ArrivalTime: "07:55",
        DepartureTime: "07:55",
        TrainType: 0,
      },
      {
        Sequence: 27,
        ArrivalTime: "07:58",
        DepartureTime: "07:58",
        TrainType: 0,
      },
      {
        Sequence: 28,
        ArrivalTime: "08:04",
        DepartureTime: "08:04",
        TrainType: 0,
      },
      {
        Sequence: 29,
        ArrivalTime: "08:07",
        DepartureTime: "08:07",
        TrainType: 0,
      },
      {
        Sequence: 30,
        ArrivalTime: "08:10",
        DepartureTime: "08:10",
        TrainType: 0,
      },
      {
        Sequence: 31,
        ArrivalTime: "08:16",
        DepartureTime: "08:16",
        TrainType: 0,
      },
      {
        Sequence: 32,
        ArrivalTime: "08:19",
        DepartureTime: "08:19",
        TrainType: 0,
      },
      {
        Sequence: 33,
        ArrivalTime: "08:22",
        DepartureTime: "08:22",
        TrainType: 0,
      },
      {
        Sequence: 34,
        ArrivalTime: "08:28",
        DepartureTime: "08:28",
        TrainType: 0,
      },
      {
        Sequence: 35,
        ArrivalTime: "08:31",
        DepartureTime: "08:31",
        TrainType: 0,
      },
      {
        Sequence: 36,
        ArrivalTime: "08:34",
        DepartureTime: "08:34",
        TrainType: 0,
      },
      {
        Sequence: 37,
        ArrivalTime: "08:40",
        DepartureTime: "08:40",
        TrainType: 0,
      },
      {
        Sequence: 38,
        ArrivalTime: "08:43",
        DepartureTime: "08:43",
        TrainType: 0,
      },
      {
        Sequence: 39,
        ArrivalTime: "08:49",
        DepartureTime: "08:49",
        TrainType: 0,
      },
      {
        Sequence: 40,
        ArrivalTime: "08:53",
        DepartureTime: "08:53",
        TrainType: 0,
      },
      {
        Sequence: 41,
        ArrivalTime: "09:01",
        DepartureTime: "09:01",
        TrainType: 0,
      },
      {
        Sequence: 42,
        ArrivalTime: "09:04",
        DepartureTime: "09:04",
        TrainType: 0,
      },
      {
        Sequence: 43,
        ArrivalTime: "09:10",
        DepartureTime: "09:10",
        TrainType: 0,
      },
      {
        Sequence: 44,
        ArrivalTime: "09:13",
        DepartureTime: "09:13",
        TrainType: 0,
      },
      {
        Sequence: 45,
        ArrivalTime: "09:19",
        DepartureTime: "09:19",
        TrainType: 0,
      },
      {
        Sequence: 46,
        ArrivalTime: "09:23",
        DepartureTime: "09:23",
        TrainType: 0,
      },
      {
        Sequence: 47,
        ArrivalTime: "09:31",
        DepartureTime: "09:31",
        TrainType: 0,
      },
      {
        Sequence: 48,
        ArrivalTime: "09:39",
        DepartureTime: "09:39",
        TrainType: 0,
      },
      {
        Sequence: 49,
        ArrivalTime: "09:45",
        DepartureTime: "09:45",
        TrainType: 0,
      },
      {
        Sequence: 50,
        ArrivalTime: "09:51",
        DepartureTime: "09:51",
        TrainType: 0,
      },
      {
        Sequence: 51,
        ArrivalTime: "10:00",
        DepartureTime: "10:00",
        TrainType: 0,
      },
      {
        Sequence: 52,
        ArrivalTime: "10:08",
        DepartureTime: "10:08",
        TrainType: 0,
      },
      {
        Sequence: 53,
        ArrivalTime: "10:15",
        DepartureTime: "10:15",
        TrainType: 0,
      },
      {
        Sequence: 54,
        ArrivalTime: "10:21",
        DepartureTime: "10:21",
        TrainType: 0,
      },
      {
        Sequence: 55,
        ArrivalTime: "10:27",
        DepartureTime: "10:27",
        TrainType: 0,
      },
      {
        Sequence: 56,
        ArrivalTime: "10:35",
        DepartureTime: "10:35",
        TrainType: 0,
      },
      {
        Sequence: 57,
        ArrivalTime: "10:43",
        DepartureTime: "10:43",
        TrainType: 0,
      },
      {
        Sequence: 58,
        ArrivalTime: "10:51",
        DepartureTime: "10:51",
        TrainType: 0,
      },
      {
        Sequence: 59,
        ArrivalTime: "10:57",
        DepartureTime: "10:57",
        TrainType: 0,
      },
      {
        Sequence: 60,
        ArrivalTime: "11:03",
        DepartureTime: "11:03",
        TrainType: 0,
      },
      {
        Sequence: 61,
        ArrivalTime: "11:11",
        DepartureTime: "11:11",
        TrainType: 0,
      },
      {
        Sequence: 62,
        ArrivalTime: "11:19",
        DepartureTime: "11:19",
        TrainType: 0,
      },
      {
        Sequence: 63,
        ArrivalTime: "11:27",
        DepartureTime: "11:27",
        TrainType: 0,
      },
      {
        Sequence: 64,
        ArrivalTime: "11:33",
        DepartureTime: "11:33",
        TrainType: 0,
      },
      {
        Sequence: 65,
        ArrivalTime: "11:39",
        DepartureTime: "11:39",
        TrainType: 0,
      },
      {
        Sequence: 66,
        ArrivalTime: "11:47",
        DepartureTime: "11:47",
        TrainType: 0,
      },
      {
        Sequence: 67,
        ArrivalTime: "11:55",
        DepartureTime: "11:55",
        TrainType: 0,
      },
      {
        Sequence: 68,
        ArrivalTime: "12:03",
        DepartureTime: "12:03",
        TrainType: 0,
      },
      {
        Sequence: 69,
        ArrivalTime: "12:09",
        DepartureTime: "12:09",
        TrainType: 0,
      },
      {
        Sequence: 70,
        ArrivalTime: "12:15",
        DepartureTime: "12:15",
        TrainType: 0,
      },
      {
        Sequence: 71,
        ArrivalTime: "12:23",
        DepartureTime: "12:23",
        TrainType: 0,
      },
      {
        Sequence: 72,
        ArrivalTime: "12:31",
        DepartureTime: "12:31",
        TrainType: 0,
      },
      {
        Sequence: 73,
        ArrivalTime: "12:39",
        DepartureTime: "12:39",
        TrainType: 0,
      },
      {
        Sequence: 74,
        ArrivalTime: "12:45",
        DepartureTime: "12:45",
        TrainType: 0,
      },
      {
        Sequence: 75,
        ArrivalTime: "12:51",
        DepartureTime: "12:51",
        TrainType: 0,
      },
      {
        Sequence: 76,
        ArrivalTime: "12:59",
        DepartureTime: "12:59",
        TrainType: 0,
      },
      {
        Sequence: 77,
        ArrivalTime: "13:07",
        DepartureTime: "13:07",
        TrainType: 0,
      },
      {
        Sequence: 78,
        ArrivalTime: "13:15",
        DepartureTime: "13:15",
        TrainType: 0,
      },
      {
        Sequence: 79,
        ArrivalTime: "13:21",
        DepartureTime: "13:21",
        TrainType: 0,
      },
      {
        Sequence: 80,
        ArrivalTime: "13:27",
        DepartureTime: "13:27",
        TrainType: 0,
      },
      {
        Sequence: 81,
        ArrivalTime: "13:35",
        DepartureTime: "13:35",
        TrainType: 0,
      },
      {
        Sequence: 82,
        ArrivalTime: "13:43",
        DepartureTime: "13:43",
        TrainType: 0,
      },
      {
        Sequence: 83,
        ArrivalTime: "13:51",
        DepartureTime: "13:51",
        TrainType: 0,
      },
      {
        Sequence: 84,
        ArrivalTime: "13:57",
        DepartureTime: "13:57",
        TrainType: 0,
      },
      {
        Sequence: 85,
        ArrivalTime: "14:03",
        DepartureTime: "14:03",
        TrainType: 0,
      },
      {
        Sequence: 86,
        ArrivalTime: "14:11",
        DepartureTime: "14:11",
        TrainType: 0,
      },
      {
        Sequence: 87,
        ArrivalTime: "14:19",
        DepartureTime: "14:19",
        TrainType: 0,
      },
      {
        Sequence: 88,
        ArrivalTime: "14:27",
        DepartureTime: "14:27",
        TrainType: 0,
      },
      {
        Sequence: 89,
        ArrivalTime: "14:33",
        DepartureTime: "14:33",
        TrainType: 0,
      },
      {
        Sequence: 90,
        ArrivalTime: "14:39",
        DepartureTime: "14:39",
        TrainType: 0,
      },
      {
        Sequence: 91,
        ArrivalTime: "14:47",
        DepartureTime: "14:47",
        TrainType: 0,
      },
      {
        Sequence: 92,
        ArrivalTime: "14:55",
        DepartureTime: "14:55",
        TrainType: 0,
      },
      {
        Sequence: 93,
        ArrivalTime: "15:03",
        DepartureTime: "15:03",
        TrainType: 0,
      },
      {
        Sequence: 94,
        ArrivalTime: "15:09",
        DepartureTime: "15:09",
        TrainType: 0,
      },
      {
        Sequence: 95,
        ArrivalTime: "15:15",
        DepartureTime: "15:15",
        TrainType: 0,
      },
      {
        Sequence: 96,
        ArrivalTime: "15:23",
        DepartureTime: "15:23",
        TrainType: 0,
      },
      {
        Sequence: 97,
        ArrivalTime: "15:31",
        DepartureTime: "15:31",
        TrainType: 0,
      },
      {
        Sequence: 98,
        ArrivalTime: "15:39",
        DepartureTime: "15:39",
        TrainType: 0,
      },
      {
        Sequence: 99,
        ArrivalTime: "15:45",
        DepartureTime: "15:45",
        TrainType: 0,
      },
      {
        Sequence: 100,
        ArrivalTime: "15:51",
        DepartureTime: "15:51",
        TrainType: 0,
      },
      {
        Sequence: 101,
        ArrivalTime: "15:59",
        DepartureTime: "15:59",
        TrainType: 0,
      },
      {
        Sequence: 102,
        ArrivalTime: "16:07",
        DepartureTime: "16:07",
        TrainType: 0,
      },
      {
        Sequence: 103,
        ArrivalTime: "16:15",
        DepartureTime: "16:15",
        TrainType: 0,
      },
      {
        Sequence: 104,
        ArrivalTime: "16:21",
        DepartureTime: "16:21",
        TrainType: 0,
      },
      {
        Sequence: 105,
        ArrivalTime: "16:27",
        DepartureTime: "16:27",
        TrainType: 0,
      },
      {
        Sequence: 106,
        ArrivalTime: "16:35",
        DepartureTime: "16:35",
        TrainType: 0,
      },
      {
        Sequence: 107,
        ArrivalTime: "16:41",
        DepartureTime: "16:41",
        TrainType: 0,
      },
      {
        Sequence: 108,
        ArrivalTime: "16:44",
        DepartureTime: "16:44",
        TrainType: 0,
      },
      {
        Sequence: 109,
        ArrivalTime: "16:51",
        DepartureTime: "16:51",
        TrainType: 0,
      },
      {
        Sequence: 110,
        ArrivalTime: "16:55",
        DepartureTime: "16:55",
        TrainType: 0,
      },
      {
        Sequence: 111,
        ArrivalTime: "16:58",
        DepartureTime: "16:58",
        TrainType: 0,
      },
      {
        Sequence: 112,
        ArrivalTime: "17:04",
        DepartureTime: "17:04",
        TrainType: 0,
      },
      {
        Sequence: 113,
        ArrivalTime: "17:07",
        DepartureTime: "17:07",
        TrainType: 0,
      },
      {
        Sequence: 114,
        ArrivalTime: "17:11",
        DepartureTime: "17:11",
        TrainType: 0,
      },
      {
        Sequence: 115,
        ArrivalTime: "17:16",
        DepartureTime: "17:16",
        TrainType: 0,
      },
      {
        Sequence: 116,
        ArrivalTime: "17:20",
        DepartureTime: "17:20",
        TrainType: 0,
      },
      {
        Sequence: 117,
        ArrivalTime: "17:23",
        DepartureTime: "17:23",
        TrainType: 0,
      },
      {
        Sequence: 118,
        ArrivalTime: "17:29",
        DepartureTime: "17:29",
        TrainType: 0,
      },
      {
        Sequence: 119,
        ArrivalTime: "17:33",
        DepartureTime: "17:33",
        TrainType: 0,
      },
      {
        Sequence: 120,
        ArrivalTime: "17:36",
        DepartureTime: "17:36",
        TrainType: 0,
      },
      {
        Sequence: 121,
        ArrivalTime: "17:42",
        DepartureTime: "17:42",
        TrainType: 0,
      },
      {
        Sequence: 122,
        ArrivalTime: "17:45",
        DepartureTime: "17:45",
        TrainType: 0,
      },
      {
        Sequence: 123,
        ArrivalTime: "17:49",
        DepartureTime: "17:49",
        TrainType: 0,
      },
      {
        Sequence: 124,
        ArrivalTime: "17:54",
        DepartureTime: "17:54",
        TrainType: 0,
      },
      {
        Sequence: 125,
        ArrivalTime: "17:58",
        DepartureTime: "17:58",
        TrainType: 0,
      },
      {
        Sequence: 126,
        ArrivalTime: "18:01",
        DepartureTime: "18:01",
        TrainType: 0,
      },
      {
        Sequence: 127,
        ArrivalTime: "18:07",
        DepartureTime: "18:07",
        TrainType: 0,
      },
      {
        Sequence: 128,
        ArrivalTime: "18:11",
        DepartureTime: "18:11",
        TrainType: 0,
      },
      {
        Sequence: 129,
        ArrivalTime: "18:14",
        DepartureTime: "18:14",
        TrainType: 0,
      },
      {
        Sequence: 130,
        ArrivalTime: "18:20",
        DepartureTime: "18:20",
        TrainType: 0,
      },
      {
        Sequence: 131,
        ArrivalTime: "18:23",
        DepartureTime: "18:23",
        TrainType: 0,
      },
      {
        Sequence: 132,
        ArrivalTime: "18:27",
        DepartureTime: "18:27",
        TrainType: 0,
      },
      {
        Sequence: 133,
        ArrivalTime: "18:32",
        DepartureTime: "18:32",
        TrainType: 0,
      },
      {
        Sequence: 134,
        ArrivalTime: "18:36",
        DepartureTime: "18:36",
        TrainType: 0,
      },
      {
        Sequence: 135,
        ArrivalTime: "18:39",
        DepartureTime: "18:39",
        TrainType: 0,
      },
      {
        Sequence: 136,
        ArrivalTime: "18:45",
        DepartureTime: "18:45",
        TrainType: 0,
      },
      {
        Sequence: 137,
        ArrivalTime: "18:49",
        DepartureTime: "18:49",
        TrainType: 0,
      },
      {
        Sequence: 138,
        ArrivalTime: "18:52",
        DepartureTime: "18:52",
        TrainType: 0,
      },
      {
        Sequence: 139,
        ArrivalTime: "18:58",
        DepartureTime: "18:58",
        TrainType: 0,
      },
      {
        Sequence: 140,
        ArrivalTime: "19:01",
        DepartureTime: "19:01",
        TrainType: 0,
      },
      {
        Sequence: 141,
        ArrivalTime: "19:05",
        DepartureTime: "19:05",
        TrainType: 0,
      },
      {
        Sequence: 142,
        ArrivalTime: "19:11",
        DepartureTime: "19:11",
        TrainType: 0,
      },
      {
        Sequence: 143,
        ArrivalTime: "19:14",
        DepartureTime: "19:14",
        TrainType: 0,
      },
      {
        Sequence: 144,
        ArrivalTime: "19:17",
        DepartureTime: "19:17",
        TrainType: 0,
      },
      {
        Sequence: 145,
        ArrivalTime: "19:24",
        DepartureTime: "19:24",
        TrainType: 0,
      },
      {
        Sequence: 146,
        ArrivalTime: "19:27",
        DepartureTime: "19:27",
        TrainType: 0,
      },
      {
        Sequence: 147,
        ArrivalTime: "19:31",
        DepartureTime: "19:31",
        TrainType: 0,
      },
      {
        Sequence: 148,
        ArrivalTime: "19:37",
        DepartureTime: "19:37",
        TrainType: 0,
      },
      {
        Sequence: 149,
        ArrivalTime: "19:41",
        DepartureTime: "19:41",
        TrainType: 0,
      },
      {
        Sequence: 150,
        ArrivalTime: "19:45",
        DepartureTime: "19:45",
        TrainType: 0,
      },
      {
        Sequence: 151,
        ArrivalTime: "19:50",
        DepartureTime: "19:50",
        TrainType: 0,
      },
      {
        Sequence: 152,
        ArrivalTime: "19:54",
        DepartureTime: "19:54",
        TrainType: 0,
      },
      {
        Sequence: 153,
        ArrivalTime: "19:58",
        DepartureTime: "19:58",
        TrainType: 0,
      },
      {
        Sequence: 154,
        ArrivalTime: "20:04",
        DepartureTime: "20:04",
        TrainType: 0,
      },
      {
        Sequence: 155,
        ArrivalTime: "20:10",
        DepartureTime: "20:10",
        TrainType: 0,
      },
      {
        Sequence: 156,
        ArrivalTime: "20:15",
        DepartureTime: "20:15",
        TrainType: 0,
      },
      {
        Sequence: 157,
        ArrivalTime: "20:22",
        DepartureTime: "20:22",
        TrainType: 0,
      },
      {
        Sequence: 158,
        ArrivalTime: "20:29",
        DepartureTime: "20:29",
        TrainType: 0,
      },
      {
        Sequence: 159,
        ArrivalTime: "20:35",
        DepartureTime: "20:35",
        TrainType: 0,
      },
      {
        Sequence: 160,
        ArrivalTime: "20:41",
        DepartureTime: "20:41",
        TrainType: 0,
      },
      {
        Sequence: 161,
        ArrivalTime: "20:47",
        DepartureTime: "20:47",
        TrainType: 0,
      },
      {
        Sequence: 162,
        ArrivalTime: "20:52",
        DepartureTime: "20:52",
        TrainType: 0,
      },
      {
        Sequence: 163,
        ArrivalTime: "21:00",
        DepartureTime: "21:00",
        TrainType: 0,
      },
      {
        Sequence: 164,
        ArrivalTime: "21:05",
        DepartureTime: "21:05",
        TrainType: 0,
      },
      {
        Sequence: 165,
        ArrivalTime: "21:12",
        DepartureTime: "21:12",
        TrainType: 0,
      },
      {
        Sequence: 166,
        ArrivalTime: "21:20",
        DepartureTime: "21:20",
        TrainType: 0,
      },
      {
        Sequence: 167,
        ArrivalTime: "21:27",
        DepartureTime: "21:27",
        TrainType: 0,
      },
      {
        Sequence: 168,
        ArrivalTime: "21:34",
        DepartureTime: "21:34",
        TrainType: 0,
      },
      {
        Sequence: 169,
        ArrivalTime: "21:40",
        DepartureTime: "21:40",
        TrainType: 0,
      },
      {
        Sequence: 170,
        ArrivalTime: "21:48",
        DepartureTime: "21:48",
        TrainType: 0,
      },
      {
        Sequence: 171,
        ArrivalTime: "21:55",
        DepartureTime: "21:55",
        TrainType: 0,
      },
      {
        Sequence: 172,
        ArrivalTime: "22:02",
        DepartureTime: "22:02",
        TrainType: 0,
      },
      {
        Sequence: 173,
        ArrivalTime: "22:08",
        DepartureTime: "22:08",
        TrainType: 0,
      },
      {
        Sequence: 174,
        ArrivalTime: "22:15",
        DepartureTime: "22:15",
        TrainType: 0,
      },
      {
        Sequence: 175,
        ArrivalTime: "22:21",
        DepartureTime: "22:21",
        TrainType: 0,
      },
      {
        Sequence: 176,
        ArrivalTime: "22:28",
        DepartureTime: "22:28",
        TrainType: 0,
      },
      {
        Sequence: 177,
        ArrivalTime: "22:34",
        DepartureTime: "22:34",
        TrainType: 0,
      },
      {
        Sequence: 178,
        ArrivalTime: "22:41",
        DepartureTime: "22:41",
        TrainType: 0,
      },
      {
        Sequence: 179,
        ArrivalTime: "22:47",
        DepartureTime: "22:47",
        TrainType: 0,
      },
      {
        Sequence: 180,
        ArrivalTime: "22:54",
        DepartureTime: "22:54",
        TrainType: 0,
      },
      {
        Sequence: 181,
        ArrivalTime: "23:00",
        DepartureTime: "23:00",
        TrainType: 0,
      },
      {
        Sequence: 182,
        ArrivalTime: "23:08",
        DepartureTime: "23:08",
        TrainType: 0,
      },
      {
        Sequence: 183,
        ArrivalTime: "23:18",
        DepartureTime: "23:18",
        TrainType: 0,
      },
      {
        Sequence: 184,
        ArrivalTime: "23:24",
        DepartureTime: "23:24",
        TrainType: 0,
      },
      {
        Sequence: 185,
        ArrivalTime: "23:36",
        DepartureTime: "23:36",
        TrainType: 0,
      },
      {
        Sequence: 186,
        ArrivalTime: "23:48",
        DepartureTime: "23:48",
        TrainType: 0,
      },
      {
        Sequence: 187,
        ArrivalTime: "00:00",
        DepartureTime: "00:00",
        TrainType: 0,
      },
    ],
    ServiceDay: {
      ServiceTag: "平日",
      Monday: true,
      Tuesday: true,
      Wednesday: true,
      Thursday: true,
      Friday: true,
      Saturday: false,
      Sunday: false,
      NationalHolidays: false,
    },
    SrcUpdateTime: "2025-11-10T00:00:00+08:00",
    UpdateTime: "2025-11-07T22:36:53+08:00",
    VersionID: 30,
  },
  {
    RouteID: "G-2",
    LineID: "G",
    StationID: "G08",
    StationName: {
      Zh_tw: "台電大樓",
      En: "Taipower Building",
    },
    Direction: 0,
    DestinationStaionID: "G19",
    DestinationStationName: {
      Zh_tw: "松山",
      En: "Songshan",
    },
    Timetables: [
      {
        Sequence: 1,
        ArrivalTime: "07:16",
        DepartureTime: "07:16",
        TrainType: 0,
      },
      {
        Sequence: 2,
        ArrivalTime: "07:28",
        DepartureTime: "07:28",
        TrainType: 0,
      },
      {
        Sequence: 3,
        ArrivalTime: "07:40",
        DepartureTime: "07:40",
        TrainType: 0,
      },
      {
        Sequence: 4,
        ArrivalTime: "07:52",
        DepartureTime: "07:52",
        TrainType: 0,
      },
      {
        Sequence: 5,
        ArrivalTime: "08:04",
        DepartureTime: "08:04",
        TrainType: 0,
      },
      {
        Sequence: 6,
        ArrivalTime: "08:16",
        DepartureTime: "08:16",
        TrainType: 0,
      },
      {
        Sequence: 7,
        ArrivalTime: "08:28",
        DepartureTime: "08:28",
        TrainType: 0,
      },
      {
        Sequence: 8,
        ArrivalTime: "08:40",
        DepartureTime: "08:40",
        TrainType: 0,
      },
      {
        Sequence: 9,
        ArrivalTime: "08:52",
        DepartureTime: "08:52",
        TrainType: 0,
      },
      {
        Sequence: 10,
        ArrivalTime: "09:04",
        DepartureTime: "09:04",
        TrainType: 0,
      },
      {
        Sequence: 11,
        ArrivalTime: "17:03",
        DepartureTime: "17:03",
        TrainType: 0,
      },
      {
        Sequence: 12,
        ArrivalTime: "17:16",
        DepartureTime: "17:16",
        TrainType: 0,
      },
      {
        Sequence: 13,
        ArrivalTime: "17:28",
        DepartureTime: "17:28",
        TrainType: 0,
      },
      {
        Sequence: 14,
        ArrivalTime: "17:42",
        DepartureTime: "17:42",
        TrainType: 0,
      },
      {
        Sequence: 15,
        ArrivalTime: "17:55",
        DepartureTime: "17:55",
        TrainType: 0,
      },
      {
        Sequence: 16,
        ArrivalTime: "18:07",
        DepartureTime: "18:07",
        TrainType: 0,
      },
      {
        Sequence: 17,
        ArrivalTime: "18:20",
        DepartureTime: "18:20",
        TrainType: 0,
      },
      {
        Sequence: 18,
        ArrivalTime: "18:33",
        DepartureTime: "18:33",
        TrainType: 0,
      },
      {
        Sequence: 19,
        ArrivalTime: "18:45",
        DepartureTime: "18:45",
        TrainType: 0,
      },
      {
        Sequence: 20,
        ArrivalTime: "18:58",
        DepartureTime: "18:58",
        TrainType: 0,
      },
      {
        Sequence: 21,
        ArrivalTime: "19:11",
        DepartureTime: "19:11",
        TrainType: 0,
      },
    ],
    ServiceDay: {
      ServiceTag: "平日",
      Monday: true,
      Tuesday: true,
      Wednesday: true,
      Thursday: true,
      Friday: true,
      Saturday: false,
      Sunday: false,
      NationalHolidays: false,
    },
    SrcUpdateTime: "2025-11-10T00:00:00+08:00",
    UpdateTime: "2025-11-07T22:36:53+08:00",
    VersionID: 30,
  },
  {
    RouteID: "G-2",
    LineID: "G",
    StationID: "G19",
    StationName: {
      Zh_tw: "松山",
      En: "Songshan",
    },
    Direction: 1,
    DestinationStaionID: "G08",
    DestinationStationName: {
      Zh_tw: "台電大樓",
      En: "Taipower Building",
    },
    Timetables: [
      {
        Sequence: 1,
        ArrivalTime: "06:49",
        DepartureTime: "06:49",
        TrainType: 0,
      },
      {
        Sequence: 2,
        ArrivalTime: "07:01",
        DepartureTime: "07:01",
        TrainType: 0,
      },
      {
        Sequence: 3,
        ArrivalTime: "07:13",
        DepartureTime: "07:13",
        TrainType: 0,
      },
      {
        Sequence: 4,
        ArrivalTime: "07:25",
        DepartureTime: "07:25",
        TrainType: 0,
      },
      {
        Sequence: 5,
        ArrivalTime: "07:37",
        DepartureTime: "07:37",
        TrainType: 0,
      },
      {
        Sequence: 6,
        ArrivalTime: "07:49",
        DepartureTime: "07:49",
        TrainType: 0,
      },
      {
        Sequence: 7,
        ArrivalTime: "08:01",
        DepartureTime: "08:01",
        TrainType: 0,
      },
      {
        Sequence: 8,
        ArrivalTime: "08:13",
        DepartureTime: "08:13",
        TrainType: 0,
      },
      {
        Sequence: 9,
        ArrivalTime: "08:25",
        DepartureTime: "08:25",
        TrainType: 0,
      },
      {
        Sequence: 10,
        ArrivalTime: "08:37",
        DepartureTime: "08:37",
        TrainType: 0,
      },
      {
        Sequence: 11,
        ArrivalTime: "08:46",
        DepartureTime: "08:46",
        TrainType: 0,
      },
      {
        Sequence: 12,
        ArrivalTime: "08:55",
        DepartureTime: "08:55",
        TrainType: 0,
      },
      {
        Sequence: 13,
        ArrivalTime: "09:07",
        DepartureTime: "09:07",
        TrainType: 0,
      },
      {
        Sequence: 14,
        ArrivalTime: "09:16",
        DepartureTime: "09:16",
        TrainType: 0,
      },
      {
        Sequence: 15,
        ArrivalTime: "09:27",
        DepartureTime: "09:27",
        TrainType: 0,
      },
      {
        Sequence: 16,
        ArrivalTime: "09:35",
        DepartureTime: "09:35",
        TrainType: 0,
      },
      {
        Sequence: 17,
        ArrivalTime: "09:56",
        DepartureTime: "09:56",
        TrainType: 0,
      },
      {
        Sequence: 18,
        ArrivalTime: "10:04",
        DepartureTime: "10:04",
        TrainType: 0,
      },
      {
        Sequence: 19,
        ArrivalTime: "10:12",
        DepartureTime: "10:12",
        TrainType: 0,
      },
      {
        Sequence: 20,
        ArrivalTime: "16:31",
        DepartureTime: "16:31",
        TrainType: 0,
      },
      {
        Sequence: 21,
        ArrivalTime: "16:47",
        DepartureTime: "16:47",
        TrainType: 0,
      },
      {
        Sequence: 22,
        ArrivalTime: "17:01",
        DepartureTime: "17:01",
        TrainType: 0,
      },
      {
        Sequence: 23,
        ArrivalTime: "17:14",
        DepartureTime: "17:14",
        TrainType: 0,
      },
      {
        Sequence: 24,
        ArrivalTime: "17:27",
        DepartureTime: "17:27",
        TrainType: 0,
      },
      {
        Sequence: 25,
        ArrivalTime: "17:39",
        DepartureTime: "17:39",
        TrainType: 0,
      },
      {
        Sequence: 26,
        ArrivalTime: "17:52",
        DepartureTime: "17:52",
        TrainType: 0,
      },
      {
        Sequence: 27,
        ArrivalTime: "18:05",
        DepartureTime: "18:05",
        TrainType: 0,
      },
      {
        Sequence: 28,
        ArrivalTime: "18:17",
        DepartureTime: "18:17",
        TrainType: 0,
      },
      {
        Sequence: 29,
        ArrivalTime: "18:30",
        DepartureTime: "18:30",
        TrainType: 0,
      },
      {
        Sequence: 30,
        ArrivalTime: "18:43",
        DepartureTime: "18:43",
        TrainType: 0,
      },
      {
        Sequence: 31,
        ArrivalTime: "18:55",
        DepartureTime: "18:55",
        TrainType: 0,
      },
      {
        Sequence: 32,
        ArrivalTime: "19:08",
        DepartureTime: "19:08",
        TrainType: 0,
      },
      {
        Sequence: 33,
        ArrivalTime: "19:21",
        DepartureTime: "19:21",
        TrainType: 0,
      },
      {
        Sequence: 34,
        ArrivalTime: "19:33",
        DepartureTime: "19:33",
        TrainType: 0,
      },
      {
        Sequence: 35,
        ArrivalTime: "20:18",
        DepartureTime: "20:18",
        TrainType: 0,
      },
      {
        Sequence: 36,
        ArrivalTime: "20:38",
        DepartureTime: "20:38",
        TrainType: 0,
      },
      {
        Sequence: 37,
        ArrivalTime: "20:56",
        DepartureTime: "20:56",
        TrainType: 0,
      },
      {
        Sequence: 38,
        ArrivalTime: "21:16",
        DepartureTime: "21:16",
        TrainType: 0,
      },
    ],
    ServiceDay: {
      ServiceTag: "平日",
      Monday: true,
      Tuesday: true,
      Wednesday: true,
      Thursday: true,
      Friday: true,
      Saturday: false,
      Sunday: false,
      NationalHolidays: false,
    },
    SrcUpdateTime: "2025-11-10T00:00:00+08:00",
    UpdateTime: "2025-11-07T22:36:53+08:00",
    VersionID: 30,
  },
];

// set data as a global variable
window.data = data;
